dnanexus/dx-toolkit

- src/ua/chunk.cpp
@jmdale @asimenos Please review and let me know if there is any reason we shouldn't push this out to prod right now.
> Adding several configuration options which should prevent uploads from getting stuck

- src/python/dxpy/scripts/dx.py
Previously when adding a subparser it got the name of the subparser from the last item in the
_choices_actions list from the subparsers_action.  However, if a subparser does not have a help
field, like new gtable, then it won't have an entry in the subparsers_action._choices_actions
list.  Instead, it will grab the name of the previous subparser that contained a help field,
which in this case is dx new workflow.
This fix grabs the name from the prog field of the subparser instead.  I checked
all subparsers to see if their name from the prog field would match the name from
the _choices_actions list, and they all do, EXCEPT: new gtable (which was incorrect
before and the subject of this bug) and make_download_url and upgrade.  The latter two
did not match because they did not explicitly set …
> PTFM-14569 fixing dx help new workflow issue

- src/ua/chunk.cpp
@godotgildor, please add your port passthrough fix in this branch.
> PTFM-16030 TCP accelerator tunnel support in UA

- src/python/dxpy/scripts/dx.py
Removed PUBLIC as option. @psung @carriejiang please review.
> Updated helpstring for dx invite/uninvite 

- src/ua/chunk.cpp
> PTFM-17684 Print entirety of error response so we can see S3 errors

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
Allow user to specify all --debug-on options at once in dx run
https://dnanexus.jira.com/browse/PTFM-17818
> PTFM-17818 Allow user to specify all --debug-on options at once in dx run

- src/java/src/main/java/com/dnanexus/DXSearch.java
- src/java/src/test/java/com/dnanexus/DXSearchTest.java
Hello @psung ,
Here is the test and a respective fix - would be nice if you can look on that.
Thank you very much!
> PTFM-18056 java incorrect paginated search behavior

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
https://dnanexus.jira.com/browse/PTFM-17957
> PTFM-17957 Allow users to "dx uninstall" apps by ID to which they no longer have access

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
https://dnanexus.jira.com/browse/PTFM-17957
> Allow users to "dx uninstall" apps by ID without access

- src/python/dxpy/scripts/dx.py
https://dnanexus.jira.com/browse/PTFM-18184
> PTFM-18184 dx find doesn't shows help option for apps

- src/python/dxpy/scripts/dx_build_app.py
https://dnanexus.jira.com/browse/PTFM-5485
> PTFM-5485 Don't allow "description" field to shadow Readme.md

- src/python/dxpy/scripts/dx_build_app.py
https://dnanexus.jira.com/browse/PTFM-17276
> PTFM-17276 Improve dx build help message when app name is taken

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
Hello @psung ,
this is an resolution for PTFM-17632 - review at your convenience, please. Thank you!
All the best,
Ilya
> PTFM-17632 dx update project print json

- src/python/dxpy/bindings/dxfile_functions.py
Hello @psung ,
This a resolution for PTFM-16098 - review, please if have some time. Manually tested only.
All the best,
Ilya
> PTFM-16098 dx download floors percentage

- build/upgrade.sh
https://dnanexus.jira.com/browse/PTFM-13678
> PTFM-13678 Check whether user has write permissions to destination directory when upgrading dx-toolkit

- src/python/dxpy/__init__.py
DXHTTPRequest uses a global urllib3.PoolManager to actually make requests. The
PoolManager manages urllib3.ConnectionPools, reusing them when appropriate. If
a request raises an exception, the PoolManager is "cleared", which closes
every ConnectionPool it manages. In rare cases, a ConnectionPool can be
assigned to a request but then closed before the request is made. This causes
a urllib3.exceptions.ClosedPoolError to be raised, which presently is not
handled and causes the DXHTTPRequest to fail.
The ideal solution would fix the concurrency issue, but it appears to be
within urllib3 itself. So, this change just catches ClosedPoolError and
retries.
> Handle ClosedPoolError during DXHTTPRequest

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
https://dnanexus.jira.com/browse/PTFM-13821
> PTFM-13821 Clean up dx error handling

- src/python/dxpy/cli/exec_io.py
- src/python/dxpy/scripts/dx.py
- src/python/test/dxpy_testutil.py
- src/python/test/test_dxclient.py
Hello @billagee ,
this is a fix for PTFM-17435 - review at your convenience, please.
Thank you and have a nice day,
Ilya
> PTFM-17435 dx ssh respects dx user conf dir env var

- src/java/src/main/java/com/dnanexus/Nonce.java
- src/java/src/test/java/com/dnanexus/IdempotencyTest.java
@nicolasbockg, I ran your branch through the formatter. You can merge this into your branch if you haven't started working on code review fixes yet.
> Apply formatting in Eclipse

- src/python/dxpy/bindings/dxfile.py
- src/python/test/dxpy_testutil.py
- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
Hi @psung ,
this is a solution for AZURE-314 & auto-test - look if have some time, please.
Thank you and all the best,
Ilya
> AZURE-314 Upload empty files support

- src/python/scripts/dx-docker
@nicolasbockg Please take a look when you have a chance, and thanks in advance!  These are some minor improvements to output more informative error messages when certain exceptions are thrown or to perform basic sanity checks.   Tests updated and pass.
> STACK-163: Some minor dx-docker improvements

- src/python/scripts/dx-docker
@nicolasbockg Could you take a look at this when you have a chance?  Thanks in advance!
> STACK-197: Adding logging of dx-docker subcommands

- src/python/dxpy/scripts/dx_build_app.py
- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
@psung please take a look at your convenience, and thanks in advance!  This is the first draft at allowing for remote builds on 14.04 workers and I also created a companion pull request for the 'dx_app_builder' repository.
The entire test suite was run and I added a simple test for building remotely on 14.04 workers in addition.
> PTFM-17112 - Allow remote builds on 14.04 workers

- CHANGELOG.md
@nicolasbockg Please review at your convenience.   @psung @billagee Kurt J.  interest.
> DEVEX-75 - Create change log

- src/python/scripts/dx-docker
Please, review this change. Thanks.
> DEVEX-83: Handle rm option for dx-docker run

- src/python/scripts/dx-docker
Please, review this change.
I think the 2nd commit is better since, even though we potentially will have two HOME envs set, it prevents from a situation when we pass only "env -i" (if both conditions were false). The 2nd HOME env will override the first (the default one).
> DEVEX-72 Default home environment variable for dx-docker

- src/python/test/Readme.md
Hi @kpjensen ,
this is just a small spelling issue fix - thank you!
All the best,
Ilya
> Just a small spelling issue update

- src/ua/mime.cpp
Simple fix to add 'application/gzip' to the mime type dict
> DEVEX-143 1404 ua compression

- src/ua/file.cpp
Simple check if a file is 100% uploaded
> Devex 3 upload agent resume message

- src/python/dxpy/bindings/search.py
a la https://github.com/dnanexus/dx-toolkit/pull/219
> Updating dxpy.find_data_objects

- src/java/pom.xml
Using newer libraries, to match wdl4s dependencies.
> Update java library dependencies

- src/ua/api_helper.cpp
- src/ua/api_helper.h
- src/ua/ua_test.cpp
- src/ua/ua_test.h
Added the ability in the ua to display system messages as part of the
ua --test flag. The system/greet route will return messages regarding
the TLS version used to establish the connection.
> PTFM-20347 TLS version check

- src/python/dxpy/scripts/dx.py
- src/python/dxpy/ssh_tunnel_app_support.py
We are concentrating on Jupyter notebook support for now.
> Removing rstudio option

- src/python/scripts/dx-clone-asset
@godotgildor I basically took your script stripped out the '.py' extension and added a preamble to the beginning the same as `dx-docker`.  If this looks good to you I'll merge it in.
> Import Brett's clone asset script

- src/python/scripts/dx-docker
- src/python/test/test_dx-docker.py
Hi @commandlinegirl this is a PR from a branch that I had lying around to clean up some code I wrote a while back.  Interestingly, I think it might also resolve a regression that was introduced by that commit.  I added the complex quote example to the tests as well.
> dx-docker: Cleanup of quote code. Potential regression fix

- src/python/dxpy/scripts/dx.py
Could you review it at your convenience? Thanks!
> DEVEX-542 Add version & published status to dx run -h app

- contrib/perl/lib/DNAnexus/API.pm
- contrib/ruby/lib/dxruby/api.rb
- src/R/dxR/R/api.R
- src/api_wrappers/wrapper_table.json
- src/cpp/dxcpp/api.cc
- src/cpp/dxcpp/api.h
- src/java/src/main/java/com/dnanexus/DXAPI.java
- src/python/dxpy/api.py
New database api routes available from dx-toolkit through dx api ..., or through commands specified for data objects. Bindings or other supported languages were generated by make api_wrappers
> Tip 51 database apis

- contrib/perl/lib/DNAnexus/API.pm
- contrib/ruby/lib/dxruby/api.rb
- src/R/dxR/R/api.R
- src/api_wrappers/wrapper_table.json
- src/cpp/dxcpp/api.cc
- src/cpp/dxcpp/api.h
- src/java/src/main/java/com/dnanexus/DXAPI.java
- src/python/dxpy/api.py
Add auto-generated API wrappers for the new validateBatch API call
> DEVEX-573 Add API wrappers for app & workflow validateBatch

- src/java/src/main/java/com/dnanexus/DXEnvironment.java
- src/java/src/main/java/com/dnanexus/DXHTTPRequest.java
These parameters are required to prevent stuck of threads on socket read operation
Issue: https://github.com/dnanexus/dx-toolkit/issues/286
> Add socketTimeout and connectionTimeout parameters

- contrib/perl/lib/DNAnexus/API.pm
- contrib/ruby/lib/dxruby/api.rb
- src/R/dxR/R/api.R
- src/api_wrappers/wrapper_table.json
- src/cpp/dxcpp/api.cc
- src/cpp/dxcpp/api.h
- src/java/src/main/java/com/dnanexus/DXAPI.java
- src/python/dxpy/api.py
database/new and database-xxxx/update will be removed once methods will
become private. database/findByName is permanent.
> Autogenerate wrappers for missing database API methods

- src/python/scripts/dx-docker
Updating to 8 times as opposed to 3 due to some flakiness observed.
> Update dx-docker to retry more

- src/python/dxpy/__init__.py
Did not make it previously due to failing tests (which turned out coincidental). Thanks!
> DEVEX-406 Do not retry sending a request on code 422

- src/python/scripts/dx-clone-asset
**Motivation**
Multiprocessing with dxpy request encounters `SSLErrors`.
Using subprocess is a known workaround.
> SCI-744-clone-asset-ssl-error

- src/python/dxpy/bindings/dxproject.py
`set_properties()` for `dxpy.DXProject`
> DEVEX-681 DXProject.set_properties()

- src/python/dxpy/bindings/dxglobalworkflow.py
- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
I added some usage examples to the ticket.
> DEVEX-667 dx find global workflows

- src/python/test/test_dxclient.py
> DEVEX-667: Fix a failing test from 9fe76fc

- src/python/dxpy/bindings/dxfile_functions.py
> Import err_exit which is used when downloading symlinks

- src/python/dxpy/utils/describe.py
- src/python/test/test_dxclient.py
I added an example output of "dx describe" as the ticket comment.
> DEVEX-620 Print proper dx describe analysis of a global workflow

- src/python/dxpy/utils/describe.py
This addresses a comment review you made previously for [`dx describe globalworkflow`](https://github.com/dnanexus/dx-toolkit/pull/320). I added an example output to the ticket. Thanks!
> DEVEX-683 Add a note to dx describe that the workflow is locked

- src/python/test/test_dxclient.py
This commit adds a test for dx watch to ensure websocket errors are handled
correctly from the apiserver route.
A recent change to the apiserver changes the error code
for closing the websocket from 1008 to 4008.  Despite that socket closing
code being different, the client error should continue to look the same.
> PTFM-21023 dx watch job log relay test

- src/python/dxpy/scripts/dx.py
Display `cached` if job results are reused
> DEVEX-761 find executions job reuse

- src/python/requirements.txt
Note @geetduggal is on steve's computer
> dateutils version update

- .gitignore
- src/Makefile
- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
- src/python/test/wdl/trivial.wdl
Integrating dxWDL into the dx-toolkit.
> DEVEX-750 dx wdl integration

- build/pynsist_files/installer.cfg.template
`python-dateutil` was updated from 2.3 --> 2.5
> Fix Windows build

- .gitignore
- src/Makefile
- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
* Adding support for DxNI
* bumping dxWDL version to 0.69
> DEVEX-774 support dxni compilation 

- src/python/dxpy/utils/resolver.py
Add support for database data object to resolver
Fixes dx describe database-xxxx
> TIP dx describe database

- contrib/ruby/lib/dxruby/api.rb
- src/R/dxR/R/api.R
- src/api_wrappers/wrapper_table.json
- src/java/src/main/java/com/dnanexus/DXAPI.java
- src/python/dxpy/api.py
Private documentation can be found [here](https://github.com/dnanexus/nucleus/blob/master/apiserver/tip/Readme.md)
> Remove unavailable documentation links

- build/Jenkinsfile
- debian/control
Change jenkins nodes to master.
Add builder jobs for xenial deb package and regular tar.gz.
Update debian control for jdk8 with 16.04
> DEVEX-807 16.04 build

- build/Jenkinsfile
- build/build-dx-toolkit-debs.sh
Define implicit release as precise. Rewrite target releases for trusty and xenial.
> Deb package release targets

- src/python/dxpy/bindings/dxapp.py
- src/python/dxpy/bindings/dxapplet.py
- src/python/dxpy/scripts/dx.py
Support for `ignoreReuse` boolean parameter for `dx build` and `dx run`
e.g. `dx run --ignore-reuse app-cloud_workstation`
> DEVEX-821 ignore reuse

- build/Jenkinsfile
- build/build-dx-toolkit-debs.sh
This reverts commit e79e2c64fa1c0a63978aa628dfd0dc805a159dfd.
> Revert "Deb package release targets (#390)"

- src/python/dxpy/scripts/dx.py
Thanks to @jtratner for pointing this out!
> DEVEX-844 Fix generate batch inputs bug

- src/python/dxpy/scripts/dx.py
- src/python/dxpy/utils/printing.py
- src/python/test/test_dxclient.py
> Warn user before `dx rm -r` on root of a project

- src/python/requirements_test.txt
Tests run on this branch (against staging) passed.
> PTFM-22590 Upgrade pyopenssl for tests

- environment.fish
Some people use fish shell. If we want to help those people out, we should include a version of environment that works for fish. This is that thing.
> First draft of an environment file for fish shell

- .gitignore
- bin/dx-su-contrib
- src/Makefile
- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
Removing the dx commands: sh, compile, compile_dxni. These are hard to support, and rarely used.
> Removing rare subcommands

- .gitignore
- environment
Check if the register-python-argcomplete binary exists before using it.
> Argcomplete fix

- src/python/dxpy/bindings/dxfile_functions.py
https://github.com/dnanexus/dx-toolkit/issues/472
> DEVEX-1033 Limit aria2c connections to <= 16 per server for symlink downloads

- CHANGELOG.md
- build/Jenkinsfile
Remove 32-bit build for Ubuntu 14.04
> Remove i386 build target

- src/python/dxpy/cli/org.py
- src/python/dxpy/scripts/dx.py
> dx org update args fix

- src/python/dxpy/scripts/dx.py
The api route listFolder now returns modified date as millis from epoch, so we need to convert it back to readable format in the dx cmd. The apiserver PR is: https://github.com/dnanexus/nucleus/pull/2644
> TIP-1022: return modified date as millis from epoch

- src/python/dxpy/scripts/dx.py
> Convert tab in dx.py to spaces

- src/python/dxpy/bindings/__init__.py
- src/python/dxpy/scripts/dx.py
Perform fewer file describes in `dx wait`
> DEVEX-1082 Improve `dx wait` behavior

- build/upgrade.sh
Update for `dx upgrade` to download the latest release from s3.
> DEVEX-1155 Download toolkit from s3 bucket

- src/java/src/main/java/com/dnanexus/DXApplet.java
- src/java/src/main/java/com/dnanexus/DXDataObject.java
- src/java/src/main/java/com/dnanexus/DXEnvironment.java
- src/java/src/main/java/com/dnanexus/DXFile.java
- src/java/src/main/java/com/dnanexus/DXHTTPRequest.java
- src/java/src/main/java/com/dnanexus/DXRecord.java
This merges back changes made to the dxWDL fork of dxjava. There are three kinds of changes:
1. Differences between the scala/java compiler and the normal java compiler
2. Addition of support for proxies
3. Allowing disabling retries. This helps testing.
> Merge dxjava fork

- src/python/dxpy/bindings/dxfile_functions.py
- src/python/dxpy/bindings/timeout.py
This is a quick modification to allow for the timeout and retry of a file part upload.  It is still under testing.
> DEVEX-1103 -Timeout and retry upload of file part

- src/python/test/test_dxclient.py
Explicitly provide project id.
> dx make_download_url test fix

- src/python/test/test_dx_symlink.py
One of the symlink tests has been failing for a long time. Fixed it.
> Python3 test fixes

- src/python/dxpy/utils/completer.py
Update the instance table with new instance types and add missing ones, and make the numbers consistent with Documentation.
> Update the instance table with new instance types and add missing ones.

- src/python/dxpy/scripts/dx_build_app.py
> DEVEX-1401: Fix Python3 issue in dx app builder test

- src/python/dxpy/bindings/search.py
- src/python/dxpy/scripts/dx.py
This change should enable search for database data objects though `dx find data --class database`
> TIP-831 Enable database class in dx find data

- src/python/dxpy/dxlog.py
- src/python/dxpy/utils/exec_utils.py
- src/python/scripts/dx-log-stream
Python 3 execution environment support.
Add pip3 to execDepends.
Truncate joblog messages properly for streaming.
> DEVEX-1416 py3 exec env support

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dx_bash_helpers.py
- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
Passes the test suite except for the two sshing tests
> DEVEX-1422 Fix tests to support Python3

- src/python/dxpy/__init__.py
- src/python/dxpy/scripts/dx_build_app.py
- src/python/dxpy/templating/templates/python/parallelized/test/test.py
- src/python/test/dxpy_testutil.py
Adding the SSL EOF error to those that can be retried. Also, improving some python2/python3 compatibility cases.
> DEVEX-1278 retry logic dx upload

- src/python/dxpy/scripts/dx_build_app.py
Process correctly an error message from compiling a dx app.
> Fix python2/3 error

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
> DEVEX-1497 Error out for dx run --clone with analysis and executable

- doc/examples/dx-apps/python_trimmer_example/dxapp.json
- doc/examples/dx-apps/python_trimmer_example/src/python_trimmer_example.py
- src/python/scripts/dx-generate-dxapp
DEVEX-1387 documentation python2 -> python3
> DEVEX-1387 documentation python2 -> python3

- .gitignore
Begin tracking toolkit_version.py and updating it during releases.
> Remove toolkit_version.py from .gitignore

- src/python/test/behave_tests/docker-compose.yml
- src/python/test/behave_tests/features/dx.feature
- src/python/test/behave_tests/features/upload_agent.feature
- Upload agent example scenario added
- expect_error if not present by default is False
> QE-496: Upload agent scenario

- src/python/dxpy/cli/exec_io.py
Updated reference Genome files project search - searching in a certain region only
> APPS-361 - search for reference genome files proj using region

- src/java/src/main/java/com/dnanexus/DXEnvironment.java
Set reasonably high defaults for total connections and connections per route. May want to investigate more into what these values should be. 
Allow setting the `maxTotalConnection` and `maxDefaultConnectionsPerRoute` for httpclient.
> DEVEX-1894 Allow configurable max connections for httpclient

- src/python/test/test_dxclient.py
Close files in tests.
Update applet to Ubuntu 20.04
> dxclient test fixes

- src/python/test/test_dx_app_wizard.py
- src/python/test/test_dxasset.py
- src/python/test/test_dxclient.py
Cleanup some dxpy test output.
> Close files in various dxpy tests

- CHANGELOG.md
- src/python/dxpy/utils/describe.py
https://jira.internal.dnanexus.com/browse/APPS-632
> APPS-632 Adding currency formatting based on provided metadata

- src/java/pom.xml
- src/java/src/main/java/com/dnanexus/DXEnvironment.java
Update slf4j-log4j12 --> log4j2@2.17.1
Update jackson-databind -->  2.9.10.8
> DEVEX-2031 Update Java dependencies 

- CHANGELOG.md
- src/python/dxpy/bindings/dxfile_functions.py
- src/python/dxpy/cli/download.py
- src/python/dxpy/scripts/dx.py
Based on https://github.com/dnanexus/dx-toolkit/pull/709
> APPS-1157 symlink download improvements

- src/python/requirements.txt
Bump allowed requests dependency to latest version. https://github.com/dnanexus/dx-toolkit/issues/648
> DEVEX-2076 Allow requests dependency to latest 2.27.1

- CHANGELOG.md
- src/python/scripts/dx-jobutil-new-job
- src/python/test/test_dx_bash_helpers.py
* add the `--head-job-on-demand` artgument to dx-jobutil-new-job and edit a test
> APPS-1298 dx-jobutil-new-job add --head-job-on-demand argument

- CHANGELOG.md
- src/python/dxpy/bindings/dxapplet.py
- src/python/dxpy/scripts/dx.py
- src/python/test/Readme.md
- src/python/test/test_dxclient.py
* add --head-job-on-demand flag for dx run app/applet
> APPS-1290-head-job-on-demand-dx-run-option

- src/python/dxpy/scripts/dx_build_app.py
Tests failing in python 2 with `str()`
> Fix python 2 unicode error in `dx build`

- src/python/dxpy/scripts/dx.py
Accidentally delete default for dx build. Adding them back.
> APPS-1437 dx build help fix

- src/python/dxpy/templating/templates/nextflow/dxapp.json
An integration test on this branch running a simple applet passed.
> APPS-1469 Ignore reuse in the template

- src/python/dxpy/templating/templates/nextflow/src/nextflow.sh
https://staging.dnanexus.com/projects/GJ839q80QpbFg9BZ1Jk5J6Yg/monitor/job/GJFPX480QpbKZ511G7B8gzgK
> APPS-1466 print-nextflow-run-cmd

- CHANGELOG.md
- src/python/dxpy/nextflow/nextflow_builder.py
- src/python/dxpy/scripts/dx_build_app.py
- src/python/test/test_nextflow.py
manual test done:
$ dx build --nextflow --repository https://github.com/nextflow-io/hello --destination="project-FpGpg8Q0k25YQ1k53YF8YxkG:/APPS-1412"
Started builder job job-GJZQ0Kj0k25kgbqP0jPy8B2X
Created Nextflow pipeline applet-GJZQ1gj0p24vv40j2ky95ZqV
$ dx describe applet-GJZQ1gj0p24vv40j2ky95ZqV --json | jq .folder
"/APPS-1412"
$ dx describe applet-GJZQ1gj0p24vv40j2ky95ZqV --json | jq .project
"project-FpGpg8Q0k25YQ1k53YF8YxkG"
$ dx pwd
MH secret project:/MHfolder
$ dx env | grep project
Current workspace       project-GFYvg4Q0469VKVVVP359Yfpp
Test run https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/240/
> APPS-1412 destination repository

- src/python/dxpy/utils/config.py
> No parent process when used in Docker

- src/python/dxpy/nextflow/nextflow_utils.py
- src/python/dxpy/templating/templates/nextflow/src/nextflow.sh
Before merging production assets must also be built and propagated.
> APPS-1512 Update records in the Nextflow template

- src/python/dxpy/scripts/dx.py
Update help for database-ui-view-only argument in dx new project
> TIP-2606 Update help for database-ui-view-only argument

- src/python/dxpy/cli/dataset_utilities.py
TIP-3170 Removed downloadRestricted check for extract_dataset command since it is properly checking in /visualize call
> TIP-3170 Removed downloadRestricted check for extract_dataset

- src/python/dxpy/templating/templates/nextflow/dxapp.json
Test: The `test_nextflow` tests on Jenkins passed: [py2](https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-master-integration-tests-on-staging-16.04-python2/1907), [py3](https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-master-integration-tests-on-staging-20.04-python3/723/).
> APPS-1558 Set UPLOAD project permission to Nextflow applets

- src/python/dxpy/scripts/dx_build_app.py
- src/python/test/test_nextflow.py
Tests: [Py3](https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/284/), [Py2](https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-master-integration-tests-on-staging-16.04-python2/1930/).
> APPS-1560 Add dxNextflow verification

- CHANGELOG.md
- src/python/dxpy/utils/describe.py
- src/python/dxpy/utils/pretty_print.py
+ update CHANGELOG for previous tickets (DEVEX-2182 and DEVEX-2183)
> DEVEX-2185 Pretty print spotWaitTime for jobs in dx describe

- src/python/dxpy/nextflow/nextflow_builder.py
- src/python/dxpy/scripts/dx_build_app.py
Details are provided in the ticket.
> APPS-1611 Fix feature switch check for Nextflow pipeline build

- CHANGELOG.md
- src/python/dxpy/nextflow/nextaur_assets.json
- src/python/dxpy/nextflow/nextaur_assets.staging.json
- src/python/dxpy/nextflow/nextflow_assets.json
- src/python/dxpy/nextflow/nextflow_assets.staging.json
- src/python/dxpy/templating/templates/nextflow/src/nextflow.sh
nextflow tests: https://jenkins-vstg.internal.dnanexus.com/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/372/
> APPS-1698 updated nextaur

- src/python/dxpy/dx_extract_utils/turbo_filter.py
fixing a small bug I found during my testing ticket
> initializing variable

- CHANGELOG.md
- src/python/dxpy/bindings/dxapplet.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/utils/describe.py
Reverts dnanexus/dx-toolkit#972
> DEVEX-2159 Re-introduce preserveJobOutputs functionality

- src/mk/Makefile.linux
- src/python/setup.py
Reverts dnanexus/dx-toolkit#931
> Revert "DEVEX-2216 Ubuntu 22.04 + py3.10 'make python' fix"

- src/python/dxpy/cli/dataset_utilities.py
- Add payload["is_cohort"] = True for having only necessary joins
- Fix assay name and assay id selection
- Replace `hom` by `hom-alt` in query and in data output
> SCIPROD-1069, output post processing, fix assay name selection

- src/python/dxpy/dx_extract_utils/turbo_filter.py
- src/python/test/CLIGAM_tests/test_payload.py
Changes user input to upper case for case sensitive fields
> Modify user input

- src/python/dxpy/scripts/dx.py
Updates based on PR comments in pseudopod.
> SCIPROD-1288 Update help text for extract_assay germline

- src/python/dxpy/dx_extract_utils/input_validation.py
Removing usage of raw exit() function from python input validation
> using sys_exit function from exceptions.py rather than exit()

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/filter_to_payload.py
- src/python/dxpy/dx_extract_utils/input_validation.py
- src/python/test/test_extract_assay.py
Note: this PR also fixes a bug I introduced in the PR that removes instances of exit(), err_exit(1) doesn't work, needs to have a string arg or no arg
> Sciprod 1342 update method names

- src/python/dxpy/dx_extract_utils/input_validation.py
- src/python/test/extract_assay_germline/compare_output.py
- src/python/test/extract_assay_germline/test_payload.py
removing hardcoded paths, added argument parser to one-off filter test script
> removing hardcoded paths

- src/python/dxpy/cli/dataset_utilities.py
Replacing eval statement with the code suggested by Jan Stourac
> replacing eval statement

- src/python/dxpy/dx_extract_utils/input_validation.py
Fixes the redundancy pointed out by this comment: https://github.com/dnanexus/dx-toolkit/pull/1003#discussion_r1184725821
> Islistofstrings repeat

- src/python/dxpy/cli/dataset_utilities.py
addresses redundancy pointed out in this comment: https://github.com/dnanexus/dx-toolkit/pull/1003#discussion_r1184693239
> removing redundant check for whether a filter has been given

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/filter_to_payload.py
- src/python/dxpy/scripts/dx.py
addresses some minor spelling and formatting issues
> Cligam minor formatting

- src/python/dxpy/cli/dataset_utilities.py
Hi Folks,
This swaps out uses of repr(), represented here as %r, with str(), or %s.  The use of repr() is non-standard, and __repr__ is not necessarily implemented for every type of object.  Further, the output of str() will be more user-friendly
> replacing uses of repr() with str()

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/scripts/dx.py
- src/python/test/test_extract_assay.py
Hi Folks,
This change removes some redundancy in the checks for args validity.  It now only needs to check the args present in the args object
> Args list redundancy

- src/python/dxpy/cli/dataset_utilities.py
Hi folks,
Here's the change that Niranjan and I discussed, it removes a piece of the conditional block that could never be reached, and combines two error messages into one
> Sciprod 1401 combine args error msgs

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/filter_to_payload.py
- src/python/test/test_extract_assay.py
Fix Cohort filter issue and disallow list-assays and assay-name with CohortBrowser record.
> SCIPROD-1426 Fix Cohort filter issue. 

- src/python/dxpy/scripts/dx.py
- src/python/test/test_extract_assay.py
Error out when one of the required parameters is not provided. 
Remove Project IDs from test script
> SCIPROD-1431 Fix multiple bugs

- src/python/dxpy/dx_extract_utils/input_validation.py
SCIPROD-1440 fix hom-alt and half genotype types in input validation
> SCIPROD-1440 fix hom-alt and half genotype types in input validation

- src/python/dxpy/cli/dataset_utilities.py
Added implementation for `extract_assay somatic --list-assays` using `get_assay_info` with `"somatic_variant"` `assay_type`.
> SCIPROD-1343 - extract_assay somatic list assays implementation

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/input_validation_somatic.py
- src/python/dxpy/scripts/dx.py
PR for 3 tickets: SCIPROD-1339, SCIPROD-1345, SCIPROD-1456. I put all 3 tickets together to avoid merge conflicts. Contains work for output processing, --sql, cohort browser support, hardcoded payload and some entry point changes.
> SCIPROD-1339, SCIPROD-1345, SCIPROD-1456

- src/python/dxpy/dx_extract_utils/somatic_filter_payload.py
- src/python/test/test_extract_somatic.py
Hi Folks,
This PR implements the changes Niranjan requested on the CLISAM PR
> Pmux 1324 pr comments

- src/python/dxpy/dx_extract_utils/somatic_filter_payload.py
- src/python/test/test_extract_somatic.py
PR to address python2 compatibility issues discovered in testing
> forcing values to str to avoid unicode issue, pipe issue in test

- src/python/test/test_extract_somatic.py
PR to fix creation of output directory bug
> fixing creation of output directory

- src/python/dxpy/dx_extract_utils/somatic_filter_payload.py
Hi Folks,
This PR adds a sort order to the CLISAM output, as [specified here](https://jira.internal.dnanexus.com/browse/SCIPROD-1501)
> adding order_by section to somatic filter payload

- src/python/dxpy/scripts/dx.py
Undoes the Python Black linting that had been accidentally performed on dx.py
> undoing linting changes

- src/python/dxpy/bindings/dxapplet.py
(fix) dxapplet.py - missing attr and failing test
> APPS-1859 Tree turnaround time threshold HOTFIX

- COPYING
We are missing Licensor and year in license file, this PR is addressing it.
> QE-XXXX fixed licensor in license

- src/python/dxpy/cli/dataset_utilities.py
dxpy CLI dataset utilities function to get SQL statement for a cohort filter payload
- Added function `cohort_query_api_call`.
- Merged implementation with `raw_query_api_call` by call to `query_api_call`.
> SCIPROD-1586: [CLIBCO] SQL from  cohort query API

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/cohort_filter_payload.py
Added stub code for payload creation in `create_cohort`.
> SCIPROD-1585 (INITIAL) dx create_cohort stub in payload creation

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/scripts/dx.py
Reverts dnanexus/dx-toolkit#1144
Work on this wasn't actually completed until yesterday
> Revert "SCIPROD-1583 Logic added to create_cohort to validate cohort ids via vizserver search"

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/cohort_filter_payload.py
Draft implementation of cohort creation filter and SQL query generation.
- Define arguments for cohort creation filter generation
- Combine cohort primary entity/field filters with existing filter structures defined in SCIPROD-1584 to date
> SCIPROD-1585: CLIBCO Implement Filter Payload (second draft)

- src/python/dxpy/cli/dataset_utilities.py
- src/python/test/test_create_cohort.py
Extended existing positive e2e tests to parse record-id from stdout and then delete  - this covers testing the functionality.
> SCIPROD-1603 [CLIBCO] test new record

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/Homo_sapiens_genes_manifest_staging_vep.json
- src/python/dxpy/dx_extract_utils/Homo_sapiens_genes_manifest_vep.json
- src/python/dxpy/dx_extract_utils/filter_to_payload.py
- src/python/dxpy/dx_extract_utils/retrieve_bins.py
- src/python/dxpy/dx_extract_utils/somatic_filter_payload.py
- src/python/test/test_extract_assay.py
- src/python/test/test_extract_somatic.py
Added optimization logic to dx extract_assay somatic
> SCIPROD-1614, SCIPROD-1615, SCIPROD-1679 Added optimization logic to dx extract_assay somatic, bug fix

- src/python/dxpy/cli/dataset_utilities.py
- src/python/test/test_create_cohort.py
Hi adding a test for creating filters - this examines a flow of: 
`creating filter -> cohort query -> new record`
> SCIPROD-1594: [CLIBCO] test create filter

- src/python/dxpy/cli/dataset_utilities.py
- src/python/test/test_create_cohort.py
Test for ensuring proper stdout base on `--brief` `--verbose` or default parameters.
> SCIPROD-1606:[CLIBCO] brief verbose test

- src/python/dxpy/cli/dataset_utilities.py
Adding default for `destination folder`
> SCIPROD-1589 [CLIBCO] path options

- CHANGELOG.md
- src/python/dxpy/nextflow/nextaur_assets.json
- src/python/dxpy/nextflow/nextaur_assets.staging.json
- src/python/dxpy/templating/templates/nextflow/src/nextflow.sh
Tests passed -- details in APPS-2247, APPS-2255
> APPS-2247 Release Nextaur 1.6.9

- CHANGELOG.md
- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/utils/resolver.py
Reverts dnanexus/dx-toolkit#1255
> Revert "SCIPROD-1750 catching exception caused by resolve_existing_path failing"

- CHANGELOG.md
- src/python/dxpy/nextflow/nextaur_assets.staging.json
(feat) nextaur_assets.staging.json - nextaur 1.7.0-beta update on stg
> APPS-2289 nextaur 1.7.0-beta on STG

- CHANGELOG.md
- src/python/dxpy/nextflow/nextaur_assets.staging.json
(fix) nextaur_assets.staging.json - revert back to 1.6.9
> APPS-2289_revert_nextaur_assets

- CHANGELOG.md
- src/python/dxpy/cli/dataset_utilities.py
Passing E2E: https://github.com/dnanexus/pseudopod/actions/runs/7183980076
> SCIPROD-1874: [CLIEXPRESS] Wrong ASSAY_NAME and ASSAY_ID in multi assay

- src/python/test/test_nextflow.py
(fix) test_nextflow.py - fixture update
> HOTFIX_cache-docker_fixture_update

- src/python/test/dxpy_testutil.py
- src/python/test/test_nextflow.py
(fix) test_nextflow.py - fixed failing test
> Fix test_dx_build_nextflow_from_local_cache_docker

- CHANGELOG.md
- src/python/dxpy/nextflow/nextaur_assets.json
- src/python/dxpy/nextflow/nextaur_assets.staging.json
> APPS-2448 Hotfix - Release Nextaur 1.7.3

- src/python/dxpy/scripts/dx.py
Adding arguments for genotype inferring functionality.
> SCIPROD-1898 GENOMOD add --infer-ref and --infer-nocall args

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/filter_to_payload.py
- src/python/dxpy/scripts/dx.py
- src/python/test/test_extract_assay.py
Further validation for infer ref/nocall flags
> SCIPROD-1899 [GENOMOD] Add sub logic and error messages for dxpy extract_assay germline --infer-ref and --infer-nocall arguments

- src/python/scripts/dx-jobutil-get-identity-token
- src/python/test/jwt/run.sh
> APPS-2510 Fix dx-jobutil-get-identity-token - subject_claims is empty array

- CHANGELOG.md
- src/python/dxpy/templating/templates/nextflow/dxapp.json
> APPS-2511 Remove "allProjects": "VIEW" from Nextflow Pipeline Applet

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/filter_to_payload.py
- src/python/dxpy/dx_extract_utils/germline_utils.py
- src/python/test/test_extract_assay.py
Updated genotype_only filter generation and ref sequence query to handle no genotypes returned.
> SCIPROD-1896: updated genotype_only filter and ref query

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/input_validation.py
- src/python/test/test_extract_assay.py
Redirect infering options warnings to stderr.
> SCIPROD-2021 [GENOMOD] Redirect warnings to stderr

- src/python/dxpy/scripts/dx.py
- src/python/dxpy/scripts/dx_build_app.py
fix docstring for `--cache-docker`
> APPS-2539, APPS-2540 docstrings fix for cache-docker

- CHANGELOG.md
- src/python/dxpy/nextflow/nextaur_assets.json
- src/python/dxpy/nextflow/nextaur_assets.staging.json
- src/python/dxpy/nextflow/nextflow_utils.py
Testing details on Jira - APPS-2655
> APPS-2655 Release - Nextaur 1.9.1, APPS-2657 Nextflow - quick fix asset-environment detection

- CHANGELOG.md
- src/python/dxpy/templating/templates/nextflow/src/nextflow.sh
Details, testing on Jira - APPS-2578
> APPS-2578 Nextflow Pipeline Applet script - refactor for readability

- src/python/dxpy/bindings/dxfile.py
> PTFM-38776 dx upload bugfix

- src/python/dxpy/scripts/dx.py
[PTFM-38840](https://jira.internal.dnanexus.com/browse/PTFM-38840) Update dx CLI to allow passing drive for symlink 2.0 projects
> PTFM-38840 Update dx CLI to allow passing drive for symlink 2.0 projects

- src/python/dxpy/cli/cp.py
- src/python/dxpy/scripts/dx.py
https://jira.internal.dnanexus.com/browse/PTFM-38976
PTFM-38976 Update clone/move CLI to accept targetFileRelocation flag.
> PTFM-38976 Update clone/move CLI to accept targetFileRelocation flag.

- src/python/dxpy/bindings/dxfile.py
> [DEVEX-2412] DXFile.read not respecting provided project context

- CHANGELOG.md
- src/python/dxpy/scripts/dx_app_wizard.py
- src/python/test/test_dx_app_wizard.py
> [DEVEX-2463] dx-app-wizard should generate template with AEE 24.04 by default

- CHANGELOG.md
- src/java/Readme.md
- src/java/pom.xml
- src/java/src/main/java/com/dnanexus/DXHTTPRequest.java
ticket - [COMPUTE-1233](https://jira.internal.dnanexus.com/browse/COMPUTE-1233)
- Added increased retry after timeout up to 5x higher that was returned from api server.
> COMPUTE-1233: Add Java sdk support 429 response code from platform

- build/run_traceability_integration_tests.sh
Update marker used by tests to execute the correct selection.
> COMPUTE-1600: Fix marker used by tests
