dnanexus/dx-toolkit

- build/centos_install_python27.sh
Python doesn't seem to make `bz2` files available anymore.
> Fix the build/centos_install_python27.sh script

- src/python/dxpy/bindings/__init__.py
- src/python/dxpy/bindings/download_all_inputs.py
- src/python/scripts/dx-download-all-inputs
Currently bash has access to a cool helper function called dx-download-all-inputs.  It would be nice if python based apps/applets could also make use of the same framework.
I have moved most of the dx-download-all-inputs code into the python bindings so that python apps/applets can now run
dxpy.download_all_inputs() and receive the same functionality as the bash helper function.
The bash helper function was modified so that it simply calls this function now, passing in the arguments from the command line.
> Making download_all_inputs available from within dxpy.

- src/python/dxpy/bindings/dxfile_functions.py
> dxpy.download_dxfile: handle files with no part md5 metadata

- src/python/dxpy/scripts/dx.py
- src/python/dxpy/utils/app_unbuilder.py
Add a simple command line argument to dx get to allow users to fetch
the applet without the resources.
> Add omit-resources feature

- src/python/scripts/dx-download-all-inputs
- src/python/scripts/dx-upload-all-outputs
ensure log messages appear in a timely fashion while live-streaming job logs, for situational awareness in large transfers
@orodeh @asimenos
> bash helpers: flush log messages before starting file transfers

- src/python/dxpy/__init__.py
- src/python/dxpy/scripts/dx.py
Made the following changes:
1. Bug fix for checking version of readline module.  pyreadline module does not have __doc__ variable, so need to check that it's not NONE before searching for libedit.
2. Adding ability to specify protocol to dx logout, just as you can for dx login.
3. Setting default protocol for authserver communication to https. Can be overriden by explicitly passing in a different protocol, but will no longer make assumptions based upon port.
4. Use the same get_auth_server_name helper function in dx login as we use in dx logout code.
5. Add support for China staging api and corresponding auth server to the get_auth_server_name helper function.
> Updating dx

- src/python/dxpy/scripts/dx.py
To resume an interupted download, somewhat confusingly we use the -f or --overwrite flag.
I have updated the help message for this switch to specifically mention that it will resume
the file download if possible.  Long term we may want to either rename this option or separate
the two behaviors, but at least for now this adds some clarity.
> Updating download help message.

- src/python/dxpy/scripts/dx.py
@psung, can you review this small change? A (hopefully) non-breaking change to the `dx find data` helpstring
> Removed gtable option from dx find data

- src/python/dxpy/scripts/dx_app_wizard.py
Apps should have a default timeout policy, so this change will add this field to dxapp.json when using dx-app-wizard.  We've set the default to 24 hours which should be sufficient for the vast majority of apps/applets.
> Add a default timeout policy to dx-app-wizard

- src/python/dxpy/bindings/dxfile.py
- src/python/test/test_dxpy.py
We were erroneously reporting KB, MB, GB, and TB when we really meant
KiB, MiB, GiB, and TiB.
> Fixing label for file size

- .gitignore
- src/python/dxpy/bindings/dxfile_functions.py
- src/python/dxpy/scripts/dx.py
Allow performing a dx upload, while setting the buffer chunk size. This should significantly reduce the overhead on the backend database when uploading large files. This is a situation we run into while executing parallel GLnexus runs.
> Export upload file buffer size to cli

- src/python/dxpy/asset_builder.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/scripts/dx_build_app.py
Currently both the asset builder and our remote app/applet builder code paths automatically run "dx watch" on the jobs that are building either the asset or app/applet.   Some customers are sitting behind firewalls that prohibit WebSockets traffic and are therefore unable to run "dx watch".  This causes the asset building and remote app/applet building paths to fail in their environment.
This simple pull request adds a "--skip-watch" flag to these two tools so that one can optionally skip watching the jobs that are building the assets or app/applets.  The code will still wait for the job to complete, but it will remain quiet while the jobs run.
> Allow disabling "watch" on remote builds

- src/python/dxpy/bindings/dxdataobject_functions.py
- src/python/test/test_dxpy.py
A previous commit added the system_describe_data_objects method to the api module, allowing somewhat easier access to the bulk describeDataObjects API method.  This commit extends this so that users can make use of dxpy.describe() on a list of dxlinks or object-id's to get a list of descriptions back.  This parallels nicely with the existing dxpy.describe function.
Unit test is included.
> Adding bulk data object describe to dxpy.describe

- src/python/dxpy/scripts/dx_app_wizard.py
- src/python/test/test_dx_app_wizard_and_run_app_locally.py
@psung Please review at your convenience. This commit has the affect of reverting https://github.com/dnanexus/dx-toolkit/commit/8d43eba5141b8ad0b5254f7fa910f7a49bfe7bc3 and https://github.com/dnanexus/dx-toolkit/commit/5522565f48deaf90c5b6ec732baac5320edde304 to enable 14.04 to be the default for `dx-app-wizard`.     Tested manually and ensured 'test_dx_app_wizard_and_run_app_locally.TestDXAppWizardAndRunAppLocally' tests ran successfully.
> PTFM-17112: Revert old commits to re-enable 14.04 as default

- src/python/scripts/dx-docker
@psung Please take a look at your convenience. This is a quick fix to `dx-docker` so that we handle the working directory properly when overriding image metadata. 
I ran into this when testing out the utility in a way I haven't before.  I also added a test to the test suite in a companion pull request.  Thanks in advance!
> dx-docker: Handle workdir properly when overriding image metadata

- src/api_wrappers/generateJavaAPIWrappers.py
- src/api_wrappers/generatePythonAPIWrappers.py
- src/java/src/main/java/com/dnanexus/DXAPI.java
- src/python/dxpy/api.py
Routes that supply a nonce should be retryable (this being the whole
point of adding the nonce). We don't do this by marking such routes as
retryable in the wrapper_table.json, since not all the language bindings
know how to generate the nonces, and this could result in bindings that
didn't supply the nonce but went ahead and considered the route to be
retryable anyway. Therefore, the *bindings generators* for each language
are responsible for marking each route as retryable if and only if they
inserted nonce generation code.
In particular, note that in the Java bindings, each API route has
multiple overloads and we added nonce support in only some of them (not
bothering to add nonce support in the older and deprecated overloads).
In this case, *only* the overloads that specifically …
> Mark routes as retryable when a nonce is supplied

- src/python/scripts/dx-docker
Other OSError exceptions could be raised, but we only want to pass if the directory exists. E.g. permission could be denied, and currently would be passed.
> dx-docker makedirs

- build/Prebuilt-Readme.md
Update docs to use consistent version number for `gcc` dependency install
> Fix inconsistent version numbers in docs

- src/python/dxpy/scripts/dx.py
We occasionally set up a tunnel over ssh to a worker.  When setting up the tunnel,
we want to exit the ssh command with the tunnel still open.  Today, when dx sees the
ssh exit, it prompts users to ask if they'd like to terminate the job.  We'd like to
be able to optionally supress this inquiry.
This commit adds a hidden command line to ssh to allow users to optionally supress this
prompt.
> Adding option for supressing running check when exiting ssh

- src/python/dxpy/bindings/dxfile.py
Add the methods `next` (Py 2.7 and older) and `__next__` (Py 3.0 and newer) to the DXFile class, completing the iteration interface.
This allows DXFile instances to be recognized as iterable and file-like for pandas functions like `read_table`. Absent this patch, `pandas.read_table` with a DXFile argument raises: "TypeError: coercing to Unicode: need string or buffer, DXFile found"
Monkey-patching the DXFile class is also a viable work-around:
```
>>> from pandas.core.dtypes.inference import is_file_like
>>> import dxpy
>>> dxf = dxpy.DXFile()
>>> is_file_like(dxf)
False
>>> dxpy.DXFile.next = next
>>> dxpy.DXFile.__next__ = next
>>> dxf = dxpy.DXFile()
>>> is_file_like(dxf)
True
```
> Make DXFile appear file-like for pandas

- src/python/dxpy/scripts/dx_app_wizard.py
OrderedDict returns a View object which is iterable but cannot be indexed. Cast to list before indexing.
Fixes #217
> Python3 compatibility in dx-app-wizard

- src/python/dxpy/bindings/search.py
The api exposes a field to the findProjects method to filter by region.  Adding this field
to our dxpy.find_projects helper to do likewise.
> Updating dxpy.find_projects

- build/Prebuilt-Readme.md
To avoid future stale versions of the Readme, the docs for pre-built version now refer to Github for info on building from source.
> Refer to Github's Readme for info on building from source

- src/python/dxpy/bindings/dxproject.py
- src/python/dxpy/cli/parsers.py
- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxpy.py
Add --download-restricted flag to dx-toolkit.
Test plan: run_integration_tests.sh --client_tests_only --tests test_dxpy.TestDXProject
> PTFM-20076: Add dx-toolkit support for downloadRestricted flag

- src/python/dxpy/app_builder.py
- src/python/test/test_dx_app_wizard_and_run_app_locally.py
**Motivation**
The `dx-app-wizard` script generates a `test/test.py` functional test template for apps. This is very useful; however, after [this commit](https://github.com/dnanexus/dx-toolkit/commit/545f4ff3f77cd4c8d25a878c2e7fd84b721cc75b) the script it generates doesn't run due to:
* *dxpy.executable_builder* import error, logic for `inline_documentation_files` was moved here. Since we call *dxpy.app_builder* from *dx_build_app.py* we never saw the missing *dxpy.executable_builder* import.
* Minor typo (wrong var used) in [this commit](https://github.com/dnanexus/dx-toolkit/commit/75ccb04c9e4f1e809dc3ff473bec95c3c2e5f07d#diff-d38613cee6417a94e5af7a9ccf728beeR532).
**Consideration**
Work-around does exist, import *dxpy.executable_builder* and specify `project` param in …
> dx-app-wizard python test template failure fix. test added. (#229)

- src/python/dxpy/asset_builder.py
- src/python/dxpy/scripts/dx.py
Many internal DNAnexus users have their default user policy set to use normal priority.  However, spot isn't available on Azure or in the China region, so when trying to build an asset in those regions, jobs are never launched.  This PR simply allow users to pass in a different priority to build_asset so that they can over-ride their default policy.
> Adding priority arg to build_asset

- src/python/dxpy/utils/exec_utils.py
dx-toolkit is pre-installed inside the job container, ignore the execdepends entry.
> Ignore installation of dx-toolkit in job container at runtime

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
This comments out tests that use workflowInputSpec/workflowOutputSpec. The toolkit itself will work well after the API change (except for the lockdown, until toolkit update), since these fields will be simply ignored.
> DEVEX-465: Temporarily update tests in prep for API change

- src/python/dxpy/bindings/dxworkflow.py
- src/python/dxpy/cli/exec_io.py
- src/python/dxpy/utils/describe.py
- src/python/dxpy/workflow_builder.py
- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
This changes naming so that it is synced up with the apiserver.
> DEVEX-436: Change workflowInputSpec to inputs and workflowOutputSpec to outputs

- CHANGELOG.md
- src/python/dxpy/__init__.py
- src/python/dxpy/exceptions.py
I added code to handle an exception that looks like this:
ProtocolError: ('Connection aborted.', error(54, 'Connection reset by peer'))
and throw a new exception with a custom message for the user to know that their TLS protocol is not supported.
> PTFM 20348 invalid tls error

- src/python/dxpy/utils/exec_utils.py
dx-toolkit apt package comes bundled with jq. Installing jq removes dx-toolkit from the job container.
> DEVEX-474 apt ignore jq

- src/python/scripts/dx-docker
Quick commit to ignore user argument if given (see https://github.com/common-workflow-language/cwltool/pull/542).  In the future we can support this.
> dx-docker: ignore user argument if given

- src/python/scripts/dx-docker
This PR basically addresses the issue here https://github.com/dnanexus/dx-toolkit/issues/252 (thanks @mr-c !) so we can eventually run all conformance tests achieve https://github.com/common-workflow-language/cwltool/pull/542.
dx-docker tests and conformance tests all pass.  @commandlinegirl could you take a look please? thanks!
> Better handling of quotes in dx-docker

- src/python/dxpy/scripts/dx.py
- src/python/dxpy/ssh_tunnel_app_support.py
* Removing datascience package support (snapshots make this obsolete)
* Allows user to specify a specific version of the notebook app to use
* Checks that the user has ssh configured and throws an error if not
* Allows user to select the traditional jupyter notebook interface or jupyter lab interface
* Changes subprocess calls to use the preferred list notation rather than string with shell=True
* Some additional comments to document processing.
> Updating jupyter notebook support

- src/python/scripts/dx-docker
Switch from `os.rename()` to `shutil.move()`
> DEVEX-495 dx-docker across mounts

- build/upload_to_pypi.sh
Pypi deprecated some of the old setuptools methods we used. #279
> Upload to pypi with twine. Use python at /usr/bin/python

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
Orgs as developers is supported now at API level so this operation should not be
blocked
> Remove error that blocks org from being added as developers

- src/python/dxpy/app_builder.py
- src/python/test/test_dxclient.py
If an asset is specified in dxapp.json using a project and path, then we should require
1. That the asset exist in the exact path specified (i.e. not look in subfolders for the given path)
2. Insist that there be only a single asset that matches the description.
Currently, it could be that a user specifies an asset like
project=project-982uq3954732894324
folder=/foo
name=my_asset
Inside of project-982uq3954732894324 there could be an asset called my_asset in the /foo folder and
also an asset in the /foo/.archive folder.  The system may return the asset from the .archive folder
and the user would be none the wiser!  This seems bad.  If a user specifies the path to an asset,
we should require it be that exact path.
> Fixing bug with asset in dxapp.json

- src/python/scripts/dx-clone-asset
**Motivation**
`dx-clone-asset` script consistently fails when region specific projects don't exist. Expected behavior is the region specific projects are created then used for the asset clone.
**Changes**
* It was just a missing return statement in the `_find_asset_project` function.
* Also decided to remove `subprocess` usage since using subprocess to call `dxpy` functions isn't as readable.
> SCI-629 clone asset fix

- src/Makefile
c-ares 1.13.0 has an issue preventing it from building on Windows (https://github.com/c-ares/c-ares/issues/119). Until the fix makes its way into a tagged release, we can keep using 1.12.0.
> Fetch c-ares 1.12.0 from c-ares.haxx.se

- src/python/dxpy/scripts/dx.py
Add a clarification on what `stage key` means in the `<stage key>.<input name>` format used with `dx run`. Also make it clear that we use 0-based indexing.
> DEVEX-612 Clarify documentation of stage key for dx run

- src/python/dxpy/utils/executable_unbuilder.py
In response to https://github.com/dnanexus/dx-toolkit/issues/314
> DEVEX-675 Fix dx get applet without execDepends

- src/python/dxpy/bindings/dxglobalworkflow.py
I accidentally didn't commit a file with the `publish()` method addition, so one test that relies on it started to fail. Thanks!
> DEVEX-667 Add publish method to global workflow bindings

- src/python/test/test_dxclient.py
It turns out that this test broke another test which counts the number of apps belonging to the test org (taking into account all apps created by the suite). The find-by-billTo is tested in another test by global workflows so I simply removed the billTo part.
> DEVEX-708 Fix test using an org

- src/python/dxpy/utils/describe.py
Not added before since we were missing 'delete' in the describe route output. This field is also included in the `dx describe app` output.
> DEVEX-683 Add delete to dx describe global workflow

- src/python/dxpy/scripts/dx.py
- src/python/dxpy/scripts/dx_build_app.py
- src/python/dxpy/workflow_builder.py
When an app was built we would print the message "To publish this app, use `dx api ....`. I replaced with `dx publish` and added a similar message to global workflow. I additionally cleaned the code a little bit. Thanks!
> DEVEX-562 Add a note about dx publish when building apps or global workflows

- src/python/dxpy/scripts/dx.py
- src/python/dxpy/scripts/dx_build_app.py
- src/python/dxpy/utils/resolver.py
- src/python/dxpy/workflow_builder.py
- src/python/test/test_dxclient.py
Currently, you have to add the "--make-default" flag to "dx publish" to set the published version as default. But making it immediately default is going to be most often used operation so we should not force the user to add this flag each time they publish. It will also make it consistent with "dx build --app --publish", which publishes the app after building and immediately makes it the default version.
> DEVEX-745 Add default flag to dx publish by default

- src/python/dxpy/scripts/dx.py
If a job is reused, when running `dx watch job-id`, instead stream the jobLog of the reused job.
> DEVEX-660 `dx watch  job-id` for reuse

- src/python/dxpy/scripts/dx.py
- src/python/scripts/dx-clone-asset
Adding ability to provide a file which contains a list of jobs or data objects upon which to wait.  
We ran into instances where we wanted to wait on a number of objects and hit bash limits on the number of characters that could be provided at the command line.  This new feature will allow us to get around that by simply specifying the longer list of jobs or data objects in a file instead of as command line arguments.
> Wait file list

- src/python/dxpy/scripts/dx.py
- src/python/dxpy/ssh_tunnel_app_support.py
small fixes that allow `dx -h` to work in Python 3 and also a couple uses of the dxpy.api module as well.
Adding test cases or generation for Python 3 might be a little beyond me - but I figure this is a pretty straightforward change :)
> Make dx tool (& dxpy imports) usable with python 3

- src/python/requirements.txt
Otherwise, hard to install this along with other packages since it uses version of requests from 2015 :(
Release notes here - http://docs.python-requests.org/en/master/community/updates/ - I assume it's safe to use (and clearly you can package it with your own locked version in the toolkit).
Alternate option would be to specify a *max* version - e.g. `requests>=2.7.0,<=2.19.1` and then redo testing when you want to expand it again.
> Allow newer versions of requests to be used

- src/python/requirements.txt
The version of python-dateutil is from 2016, which makes it hard to integrate with tools that require newer python-dateutil.
Similar to #373
Changelog here - https://dateutil.readthedocs.io/en/stable/changelog.html#version-2-5-0
> Allow newer versions of python-dateutil to be used

- src/python/requirements.txt
I think this is the last one! The version of psutil is from late 2015, which again is old enough that it hits version conflicts when attempting to install `dxpy` alongside other python packages.  Any possibility this could also be allowed to float versions?
(I've put these up in separate PRs in case you only want to accept some and not others, etc)
Changelog here - https://github.com/giampaolo/psutil/blob/master/HISTORY.rst
> Allow newer versions of psutil

- src/python/dxpy/__init__.py
- src/python/dxpy/exceptions.py
- src/python/test/test_dxpy.py
Handle `urllib3.exceptions.NewConnectionError` introduced in urllib3 version 1.12 https://pypi.org/project/urllib3/
> Handle urllib3 NewConnectionError

- src/python/requirements.txt
Later versions log error messages and will be incompatible with Python 2.7.6, 14.04 default version.
```
"/share/dnanexus/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible." 
```
Pulled from tag 2.3 here: https://github.com/pyca/cryptography/blob/2.3/src/cryptography/hazmat/primitives/constant_time.py
> Fix cryptography version <= 2.2.2

- build/pynsist_files/installer.cfg.template
- build/pynsist_files/pyapp_dnanexus.nsi.template
- src/Makefile
- src/python/requirements.txt
Download wheelfiles to directory and copy instead of individually copying hardcoded versions.
Bump requests to >= 2.8.0 since it includes at least urllib3 1.12 with `NewConnectionError` exception, otherwise `dx` will error out.
> Windows build fixes

- src/python/scripts/dx-docker
Re: https://github.com/dnanexus/dx-toolkit/issues/382 from @mr-c
Before landing I'll ensure all integration tests pass.  
I'll probably add some more code to ensure that quiet is passed through to all relevant subcommands in short order, but landing this would allow dx-docker to work with cwltool right away (see https://github.com/common-workflow-language/cwltool/blob/de509ba31bc4abebf44e9717952b1538ed539d64/cwltool/docker.py#L283)
> dx-docker allows `--quiet` option before run

- src/python/dxpy/scripts/dx.py
This is a fix to 0b85ce034e48f3a5c6f6e993b2f681af32d0848a. When a file with data object IDs is provided in path, the contents will now be read only if `--from-file` argument is added to `dx wait`.
> Fix to dx wait where a file with object IDs is provided in path

- build/pynsist_files/installer.cfg.template
- src/Makefile
Bundling Python 2.7.15 for Windows upgrades setuptools, which allows us to `pip install cryptography<=2.2.2` on Windows.
> DEVEX-834 Upgrade Win installer to Python 2.7.15

- src/python/test/test_dxclient.py
This test is running for ~50 minutes in staging. Only run it in an isolated environment where there is less data.
> Test `dx find --all-projects` in isolated env

- src/python/dxpy/app_builder.py
- src/python/dxpy/utils/executable_unbuilder.py
- src/python/test/test_dxasset.py
In bundledDepends, you can specify to only use the bundle in certain stages of an app by supplying the "stages" argument. However, this argument is not checked for when converting from an asset to a bundle, so assetDepends does not support this. 
I've updated the asset handling to support this and added a test.
> SCI-1087 add stages to asset depends

- src/python/dxpy/app_builder.py
- src/python/dxpy/scripts/dx.py
cc @geetduggal @jtratner 
In this PR I've fixed a few Python3-related issues when using `dx build` from the command line:
```
File "/Users/piotr/counsyl/dx-toolkit/src/python/dxpy/scripts/dx.py", line 2614, in build
dx_build_app.build(args)
File "/Users/piotr/counsyl/dx-toolkit/src/python/dxpy/scripts/dx_build_app.py", line 1002, in build
json.loads(args.extra_args) if args.extra_args else {})
File "/Users/piotr/counsyl/dx-toolkit/src/python/dxpy/scripts/dx_build_app.py", line 928, in _build_app
**extra_args
File "/Users/piotr/counsyl/dx-toolkit/src/python/dxpy/scripts/dx_build_app.py", line 794, in build_and_upload_locally
force_symlinks=force_symlinks) if not dry_run else []
File "/Users/piotr/counsyl/dx-toolkit/src/python/dxpy/app_builder.py", line …
```
> A few Python 3 compatibility fixes.

- src/python/dxpy/cli/__init__.py
- src/python/requirements_test.txt
- src/python/test/test_dxclient.py
I realize that Python 3 is not yet fully supported in dxpy, but there was a problem that seems to be fixed by this small PR.
Namely, the problem was the following error when using Python 3, dxpy and AWS Step Functions:
```
File "/var/task/basespace_sm/sequencing_handlers.py", line 7, in <module>
from dxpy import DXApplet
File "/var/task/dxpy/__init__.py", line 1002, in <module>
from .bindings import *
File "/var/task/dxpy/bindings/__init__.py", line 649, in <module>
from .dxfile import DXFile, DXFILE_HTTP_THREADS, DEFAULT_BUFFER_SIZE
File "/var/task/dxpy/bindings/dxfile.py", line 36, in <module>
from ..utils.resolver import object_exists_in_project
File "/var/task/dxpy/utils/resolver.py", line 34, in <module>
from ..cli import try_call, INTERACTIVE_CLI …
```
> Fix import dxpy cli

- src/python/scripts/dx-print-bash-vars
A fix that created bash variables for each of a job's inputs, only if it isn't too long. The current limit is 16KB.
> DEVEX-853 cat argument too long

- src/python/dxpy/bindings/dxproject.py
Noticed it was documented in the API specification but not actually present in the toolkit.  Tested it quickly and it appeared to work.
> Add parents param to clone method

- src/python/dxpy/exceptions.py
- src/python/dxpy/utils/job_log_client.py
- src/python/requirements.txt
We received a request from Lilly to support proxies. The only place where this is an issue is job_log_client, which uses websockets to poll the log of a running job. Currently, we use ws4py, which does not have proxy support. This PR replaces ws4py with websocket-client, which does have proxy support.
Please code review. I would hold off on merging for now. I have provided Lilly with a build of this branch and they will test it for a while.
> Replace ws4py with websocket-client library in job_log_client

- src/python/dxpy/utils/job_log_client.py
- src/python/requirements_backports.txt
This error occurred during a smoke test, related to the migration from ws4py to websockets-client. The fix is described here: https://github.com/kivy/python-for-android/issues/1107#issuecomment-326775043. I made this fix and re-ran the smoke tests, which passed: https://jenkins.internal.dnanexus.com/job/Smoke%20Test%20A%20Specific%20Nucleus%20Revision/534/
> Fix for 'No root certificates specified for verification of other-side certificates.'

- src/python/dxpy/utils/exec_utils.py
Execdepends cran packages failing to access the current repository `http://cran.us.r-project.org`.
Swapping to `http://cloud.r-project.org` per https://cran.cnr.berkeley.edu/mirrors.html
> Update cran repository

- src/python/scripts/dx-print-bash-vars
If a bash variable is long, print a warning, do not omit it.
> Long bash variables

- environment
Something I've noticed when sourcing the environment in the worker.
> DEVEX-931 Use absolute path to set argcomplete

- src/python/dxpy/__init__.py
As of 92fb2fd, all Windows dxpy installations were configured to use the CA cert list provided by the OS.
But since there are situations where we still want Windows devices to use the default certifi CA bundle, the env variable `DX_USE_OS_CA_BUNDLE` is introduced here as a way to avoid loading the certifi bundle.
> DEVEX-875 Allow Windows to use certifi CA bundle

- src/python/MANIFEST.in
Include `Readme.md` in source distribution generated for upload to pypi.
Pip installation  fails since this file is missing.
```
Processing ./dxpy-0.269.1.tar.gz
Complete output from command python setup.py egg_info:
File "<string>", line 1, in <module>
File "/private/var/folders/5p/s75xz4pn6q56pfhnl8r_ph3m0000gn/T/pip-req-build-WZTf6p/setup.py", line 53, in <module>
with open("Readme.md", "r") as fh:
IOError: [Errno 2] No such file or directory: 'Readme.md'
```
> Update MANIFEST.in to include python readme

- src/python/dxpy/app_builder.py
- src/python/dxpy/executable_builder.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/workflow_builder.py
- src/python/test/dxpy_testutil.py
- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
This PR adds support for building a multi-region global workflow using `dx build`.
If the workflow contains applets, it is still only possible to build the workflow
in one region.
> DEVEX-720 Add support for dx building a global workflow (with apps) in multiple regions

- src/python/dxpy/scripts/dx.py
The command `dx run <global-workflow> --instance-type <stage_id>=<instance type>` was not processed correctly. This commit fixes it.
> DEVEX-889 Fix setting instance types on global workflow stages

- src/python/scripts/dx-jobutil-parse-link
Not sure where you want to put tests for this, but currently dx-jobutil-parse-link always prints project.
Current:
```
bash -c 'dx-jobutil-parse-link --no-project "$(dx-jobutil-dxlink project-123:file-123)"'
project-123:file-123
```
Fixed:
```
bash -c 'dx-jobutil-parse-link --no-project "$(dx-jobutil-dxlink project-123:file-123)"'
file-123
```
cc @pkaleta who noted this bug.
> Actually do not print project with dx-jobutil-parse-link --no-project

- src/python/dxpy/bindings/download_all_inputs.py
- src/python/test/file_load/basic_except/run.sh
Fix to support `dx-download-all-inputs` with `--except` when the input variable is array:file.
Make `dirs_to_create` exclude all sub-folders (e.g. `$HOME/in/FOO/0`, `$HOME/in/FOO/1`, etc.), rather than just the major folder (e.g. `$HOME/in/FOO`)
> Fix for supporting dx-download-all-inputs --except [array:file variable]

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxpy.py
Right now I end up having users do:
```
dx api project new '{"name": "myname", "containsPHI": true}'
```
which is a little awkward to do.
Instead now you could do:
```
dx new project myname --phi
```
to have it include PHI.
Added a test case but wasn't sure how to run the tests.
In my hacky way of running it, got this to work:
```
$ pipenv install && pipenv run dx new project myname --phi
$ dx describe project-FV9Zvk80y1x2kzqP7Vy5Z89z
Result 1:
ID                  project-FV9Zvk80y1x2kzqP7Vy5Z89z
Class               project
Name                myname
Summary
Billed to           org-counsyl
Access level        ADMINISTER
Region              aws:us-east-1
Protected           false
Restricted          false
Contains PHI        true
Created             Thu Jan 31 11:37:09 2019
Created by …
```
> Support --phi flag for new projects

- src/python/dxpy/bindings/dxfile_functions.py
Attempt to strip the path from the output filename for the call to aria2c when downloading symlinks.
```
root@kjdev:/dir0# dx download test.gz
aria2c -o /dir0/test13.gz
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
9069c1|OK  |    60MiB/s|/dir0//dir0/test13.gz
```
The expected behavior would be to download test.gz to the current directory.
This seems fine but aria2c assumes `-d $(pwd)` if no directory argument is provided. 
```
root@kjdev:/dir0# aria2c -h |grep dir
-d, --dir=DIR                The directory to store the downloaded file.
Possible Values: /path/to/directory
Default: /dir0
```
Thus the file is actually downloaded to `/dir0/dir0/test.gz`
```
root@kjdev:/dir0# tree /dir0/
/dir0/
└── dir0
└── …
```
> Attempt to correct aria2c output path

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
Fixing a python3 issue, where the command line parser behaves a little bit differently when there is a missing argument.
> Devex 1034 cli parse error

- CHANGELOG.md
- src/python/dxpy/bindings/dxfile.py
- src/python/dxpy/bindings/dxfile_functions.py
- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
Address issue https://github.com/dnanexus/dx-toolkit/issues/426. 
1. Support binary mode in file open. 
2. Update the CLI to make use of binary mode on python3. By default, we assume files are binary. This will work for ASCII inputs, and gzip/tar files, which we assume are the majority. If you need to use unicode, the `--textual` flag is provided.
3. Additional tests.
> DEVEX-917 Binary files on python3

- src/python/test/test_dxclient.py
The tests were failing due to exit code and error message mismatch, the expected ones are:
```
commandlinegirl@osboxes:~/repos/dx-toolkit$ dx add
usage: dx add [-h] list_type ...
(...)
dx add: error: too few arguments
commandlinegirl@osboxes:~/repos/dx-toolkit$ echo $?
2
```
> DEVEX-1038 Fix missing argument test

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
I think this should fix this error that some users have seen by resolving project names with dx run.
```
dx run myapp -iflowcell_barcode=abc --project mytestproject -y
InvalidInput: Expected key "project" of input to be a valid DNAnexus container ID, code 422. Request Time=1550725555.61, Request ID=1550725555642-54230
```
cc @yingw
> Resolve project names in dx run --project flag

- src/java/src/test/java/com/dnanexus/DXSearchTest.java
The created timestamp is encoded at 1s resolution so sometimes the
"sortBy" test would break.
> DEVEX-974 Break ties in the created timestamp in the test

- src/python/test/test_dxclient.py
When running the whole test suite the new test `test_dx_run_specific_project`
was breaking due to project name conflicts:
```
ResolutionError: Found multiple projects with name "dxclient_test_pr\xf6ject";
please use a project ID to specify the desired project
```
Fixed it and also moved it to the TestDXRun() class.
> Fix test by creating a separate temporary project

- src/python/test/test_dx_symlink.py
Skip `test_symlinks` in isolated environment. Failing the jenkins integration test.
> Skip symlinks test in isolated environment

- src/python/dxpy/bindings/dxapp.py
- src/python/dxpy/bindings/dxapplet.py
- src/python/dxpy/bindings/dxworkflow.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/workflow_builder.py
- src/python/test/dxpy_testutil.py
- src/python/test/test_dxclient.py
This commit adds an ignoreReuse option for building and running workflows. 
I looked into the posssibility of reusing "--ignore-reuse" (that we have for apps now) but couldn't really use it without breaking customers' runs. There is an open [issue](https://bugs.python.org/issue9338) with using nargs (argparse optionals with nargs='?', '*' or '+' can't be followed by positionals) which means we cannot use one param that accepts 0 or more arguments.
If you had any other ideas on how we could do that I'd be happy to change it - thanks!
> DEVEX-1036 Add support for --ignore-reuse and --ignore-reuse-stage flags for workflows

- src/Makefile
Static proot binary built from https://github.com/jorge-lip/PRoot/commit/10ca3e88dc1d2e2b45439b181a168af6b4053b91
> DEVEX-1081 Upgrade proot to be compatible with kernel >= 4.8

- src/cpp/SimpleHttpLib/SimpleHttp.cpp
- src/cpp/dxcpp/dxcpp.cc
- src/ua/main.cpp
A libcurl's option [CURLOPT_TIMEOUT](https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html) was set to infinity for the cpp bindings http requests. This was causing UA to hang instead of timing out and retrying sending another request to the API server. This setting doesn't affect the libcurl session used for uploading chunk data [here](https://github.com/dnanexus/dx-toolkit/blob/0b85ce034e48f3a5c6f6e993b2f681af32d0848a/src/ua/chunk.cpp#L360). 
I set it to 15 minutes by default and 30 for PUT (potentially used by the binding's upload) though from a quick search I cannot find where HTTP_PUT might be used: https://github.com/dnanexus/dx-toolkit/search?q=HTTP_PUT&unscoped_q=HTTP_PUT
> DEVEX-1005 Decrease libcurl timeout

- src/python/dxpy/compat.py
- src/python/dxpy/sugar/__init__.py
- src/python/dxpy/sugar/processing.py
- src/python/dxpy/sugar/transfers.py
- src/python/test/sugar/test_processing.py
- src/python/test/sugar/test_transfers.py
This new branch is based on SCI-1321, rather than master.
* Add quote and makedirs to dxpy.compat
* Most of the changes suggested in #508 are implemented. Some exceptions:
* The tmpfile contextmanager cannot be replaced by tempfile.TemporaryFile. It is needed in situations where the tempfile needs to be written from python and then closed and read from the subprocess.
* I am still using dx commands for file upload and download when compression/decompression is involved. The python implementations of compression libraries are at least 2x slower than the system commands.
* Regarding use of bash shell for subprocesses, see comment here: https://github.com/dnanexus/dx-toolkit/pull/508#discussion_r270569217
* Regarding use of *args for passing commands, see comment here: …
> SCI-1323, SCI-1324: Add sugar transfer and processing modules

- src/java/src/main/java/com/dnanexus/DXHTTPRequest.java
Allows derived implementations to override with custom timeouts etc.
Apollo HTTP client for apiserver uses http-commons PoolingHttpClientConnectionManager which allows client to throw ConnectionTimeoutException if timeout exceeds. The timeout is passed by overridden method in derived instance of DXHttpRequest class.
See https://github.com/dnanexus/nucleus/pull/2773
> TIP-1021: support for passing httpcontext to execute operation.

- src/python/dxpy/bindings/dxfile_functions.py
- src/python/dxpy/cli/download.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/utils/resolver.py
This reduces the # of calls from 5 (below) to 2 for one file download (3 if not counting this [PR](https://github.com/dnanexus/dx-toolkit/pull/503)).
- `findDataObjects()` already returns descriptions of the objects to be downloaded. The field "parts" needs to be included in the descriptions for file objects downstream (for which we were making another `describe` call). I now request "parts" to be included in file describes when `resolve_existing_path()` is called from `download()` functions.
- folder resolution is skipped [here](https://github.com/dnanexus/dx-toolkit/pull/503)
- I also skip a check on whether the file is actually in the project, if the project was explicitly named (it is skipped when `args.lightweight` is used)
In this example the calls  1, 2, 3 will not be made with …
> DEVEX-1116 Reduce the number of API calls for dx download

- src/python/dxpy/__init__.py
The header we are getting from Azure as an output from the initial [ file-xxxx/upload](https://wiki.dnanexus.com/API-Specification-v1.0.0/Files#API-method:-/file-xxxx/upload) contains these fields:
```
{'Content-Length': '100663296',
'Content-MD5': 'PaoHSrYPnhEqtVPEp5doKg==',
'x-ms-blob-type': 'BlockBlob',
'x-ms-date': 'Mon, 06 May 2019 18:44:24 GMT'}
```
A corresponding header from AWS:
```
{'host': 'dnanexus-platform-upload-prod.s3.amazonaws.com',
'content-type': 'binary/octet-stream',
'x-amz-server-side-encryption':  ‘AES256', 
'content-md5': 'PaoHSrYPnhEqtVPEp5doKg==',
'content-length': '100663296'}
```
For urllib3 with Python3 we need to remove some of the fields, including content length, before sending the header with the request uploading a file part.
> DEVEX-1067 Fix upload issue via proxy in Azure

- src/python/dxpy/bindings/dxfile_functions.py
Swap `xrange()` for `range()` since that is what it was renamed to in Python 3.
> Remove xrange() for Python 3 compatibility

- environment
`register-python-argcomplete` resides in `/usr/bin` where dx-toolkit is installed via debian package as in the worker environment.
> DEVEX-1186 Fix autocompletion in worker environment

- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
Provide the project ID for `make_download_url` unless it is a job workspace or app container. Originally this was set to `None` in https://github.com/dnanexus/dx-toolkit/commit/b5c82db4afdda20f7a778fef1457314130cf118c but this should still allow those links to work.
> DEVEX-1101 Provide project ID for make_download_url

- src/mk/Makefile.windows
- src/python/requirements_backports.txt
- src/python/requirements_setuptools.txt
**Motivation**
The [`futures` backport](https://pypi.org/project/futures/) dependency should only be required in python2.7. 
**Changes**
This PR updates the backports requirements to specify a conditional dependency for `python` == "2.7".
> DEVEX-1206 require futures backport only in python2.7

- src/python/test/test_dxclient.py
For project affinity test with download URL which should no longer work
> Increase download URL test wait time

- src/python/requirements.txt
- src/python/scripts/dx-upload-all-outputs
- src/python/test/file_load/xattr_properties/README.md
- src/python/test/file_load/xattr_properties/dxapp.json
- src/python/test/file_load/xattr_properties/run.sh
- src/python/test/test_dx_bash_helpers.py
Add a new parameter `--xattr-properties` to `dx-upload-all-outputs`. If this argument is passed, read filesystem metadata and set `k,v` properties for each file uploaded, stripping the `user.` prefix from the key. Some additional checks may be required to make sure only user attributes are set as properties.
Add `xattr` as a dependency Linux builds of dx-toolkit, other distributions do not require it since this script only runs inside the DNAnexus execution environment.
> DEVEX-1205 xattr properties on dx-upload-all-outputs

- .gitignore
- src/python/dxpy/bindings/search.py
Note that "CONTRIBUTE" is the default `level` for `/system/findProjects` if not provided to the API method.
> Update find_projects() documentation

- src/python/dxpy/sugar/__init__.py
- src/python/dxpy/sugar/transfers.py
Fix for SCI-1867. When running in a job context, the project ID of an uploaded file (e.g. from dxpy.upload_local_file) will be a container ID, not the project ID. In this case, we do not want to generate fully-qualified links.
> Fix for bug #537

- src/python/dxpy/sugar/transfers.py
When the user does not provide a local filename to use with the dxpy.sugar.transfer.download* functions, we use the filename of the remote file, but we remove "unsafe" characters. The regular expression for identifying unsafe characters was missing '-'. The new regular expression is `r"[^\w-.]"`.
> Sci 1986 fix filename regular expression

- src/python/dxpy/cli/parsers.py
- src/python/dxpy/utils/completer.py
Use the v2 instance types by default for `dx-app-wizard`. Removed some older HDD instance types which are outdated.
> DEVEX-1248 Update app wizard with v2 instance types

- src/python/dxpy/utils/completer.py
Do not prefer v1 instance types, but allow them as valid inputs for `dx-app-wizard1
> Allow v1 instance types in dx-app-wizard

- src/python/test/test_dx-docker.py
Remove `dx-docker` tests which pull from quay.io. `docker2aci` can no longer pull images from there.
> Remove quay.io from dx-docker tests

- src/python/dxpy/scripts/dx.py
Only warn if attempting to delete an entire project, not a subfolder or file-id.
https://github.com/dnanexus/dx-toolkit/issues/549
> Fix project rm -r warning

- src/python/test/test_dxclient.py
Fixing find orgs test which broke due to a new org that was added to the init database
Fixes the following failing test:
test_find_orgs (test_dxclient.TestDXClientFind)
**Build:**
[Nucleus_Integration_Tests](https://jenkins-vstg.internal.dnanexus.com/view/NucleusBuildCop/job/Nucleus/job/BuildSheriff/job/Nucleus_Integration_Tests/2177/)
> Fixing find orgs test 

- src/python/dxpy/utils/describe.py
- src/python/test/test_dxclient.py
Remove archivalState and archivalProgress from project describe and tests.
Testing: `test_dx_describe_project`
Nucleus_Integration_Tests:
https://jenkins-vstg.internal.dnanexus.com/view/NucleusBuildCop/job/Nucleus/job/BuildSheriff/job/Nucleus_Integration_Tests/2172/
> PTFM-24811 Remove Project Describe Archival Fields

- src/python/dxpy/scripts/dx_build_app.py
We might not need the additional future app builders but I'm adding a few future versions just in case.
> Add xenial as a remote app tarball builder

- src/python/dxpy/utils/job_log_client.py
@jdidion @geetduggal  - this PR adds some brief docs for the logclient (I may have formatted them wrong) + a way to disable the `SystemExit` that gets raised when a job is failed or terminated.
We've set something up to use this client to collect and store all logs from a job and it's quite confusing that it raises a SystemExit when you find a failed job.
> Allow disabling system exit on log client

- src/python/dxpy/dxlog.py
@kpjensen I believe these ":" are accidentally introduced in recent changes. 
Cheers,
Quek
> Fix syntax error in dxlog

- src/python/dxpy/bindings/dxfile_functions.py
For 503s to be retried, retry-wait must be greater than 0 (https://github.com/aria2/aria2/blob/master/src/HttpSkipResponseCommand.cc#L224).  Doing that by default and now aria2c will retry for up to 150 seconds during a 503.  We should probably try this on a flaky symlink connection before merging to make sure all is good.
> DEVEX-1411 Retry on 503 for aria2c

- build/Jenkinsfile
- src/java/m2-settings.xml
- src/java/pom.xml
Maven switched the central repository to disable HTTP. Update to the HTTPS repo and remove the failing precise-debian build target.
> DEVEX-1443 fix java build

- build/doc_build_requirements.txt
Pin docutils <= 0.15.2 for version of sphinx.
> Fix python doc build

- src/python/dxpy/asset_builder.py
- src/python/dxpy/utils/executable_unbuilder.py
Add `runSpecVersion` key to dxasset.json. If release is `xenial` and `runSpecVersion` is `"1"`, build the asset with the corresponding v1 asset builder app.
> DEVEX-1383 asset builder for xenial v1

- src/python/dxpy/scripts/dx_app_wizard.py
- src/python/dxpy/scripts/dx_build_app.py
- src/python/dxpy/templating/python.py
- src/python/dxpy/templating/templates/python/basic/test/test.py
- src/python/dxpy/templating/templates/python/parallelized/test/test.py
- src/python/dxpy/templating/templates/python/scatter-process-gather/test/test.py
- src/python/dxpy/templating/utils.py
- src/python/test/test_dx_app_wizard.py
Adds support for 'interpreter':'python3' with 'version':'1', Ubuntu 16.04 in the toolkit. This will be replacing the old Python 2 as the default.  Tested manually the creation, building, and running of both bash and Python 3 apps.  Added tests app wizard testing script that is also run for traceability testing.
I believe documentation of the python3 support at large is a separate ticket, so this will be the only PR for this ticket.
> DEVEX-1386 'python3' support for dx-app-wizard

- src/python/dxpy/bindings/__init__.py
- src/python/dxpy/bindings/mount_all_inputs.py
- src/python/scripts/dx-mount-all-inputs
- src/python/test/file_mount/basic/Makefile
- src/python/test/file_mount/basic/README.md
- src/python/test/file_mount/basic/dxapp.json
- src/python/test/file_mount/basic/run.sh
- src/python/test/test_dx_bash_helpers.py
Add dx-mount-all-inputs script, which is similar to dx-download-all-inputs except that instead of downloading the input files, it mounts them using dxfuse. This helps the performance of apps like csv_loader and vcf_loader which deal with very large input files.
> DEVEX-1591: add dx-mount-all-inputs script (similar to dx-download-all-inputs)

- src/mk/Makefile.osx
- src/python/dxpy/cli/exec_io.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/templating/utils.py
- src/python/requirements.txt
- src/python/requirements_readline.txt
- src/python/setup.py
Move the gnureadline to requirements.txt file only for macOS. Wherever `readline` is imported, first try to import `gnureadline`
> Fix gnureadline import for macOS

- src/python/scripts/dx-upload-all-outputs
- src/python/test/file_load/xattr_properties/run.sh
Strip the first 5 chars of the xattr key "user." not with `lstrip()` which strips characters, not a substring. Fix python3 bytes compatibility.
> DEVEX-1687 Fix `dx-upload-all-outputs ---xattr-properties`

- src/java/src/main/java/com/dnanexus/DXHTTPRequest.java
When no response entity available, make this more clear in the error message. Previously, it would just show as " IOException: . "
> TIP-1447: clear error message when no response entity available

- build/Jenkinsfile
- src/python/requirements.txt
Remove 14.04 build targets. Temporarily disable Mac builds while jenkins nodes are not online.
Bump python cryptography dependency to >= 2.3.
> DEVEX-1723 Freeze 14.04 builds

- src/python/scripts/dx-clone-asset
This is to fix the error message below when running dx-toolkit in Python3:
```
multiprocessing.pool.RemoteTraceback:
"""
File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
result = (True, func(*args, **kwds))
File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
return list(map(*args))
File "/usr/local/bin/dx-clone-asset", line 96, in _clone_asset_into_region
project_id = _find_asset_project(region)
File "/usr/local/bin/dx-clone-asset", line 79, in _find_asset_project
projects = projects.split('\n')
TypeError: a bytes-like object is required, not 'str'
"""
The above exception was the direct cause of the following exception:
File "/usr/local/bin/dx-clone-asset", line 208, in <module> …
```
> Update dx-clone-asset for python3

- src/python/scripts/dx-clone-asset
Fix the checking error of whether an asset pulling project pre-exists in the target region.
> Fix error in dx-clone-asset when no asset project

- src/python/dxpy/__init__.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/ssh_tunnel_app_support.py
- src/python/scripts/dx-notebook-reconnect
Add back removed `dx notebook` and `dx loupe-viewer` commands, but hide the subparsers from `dx` help output.
> DEVEX-1769 Hide help output of `dx notebook`

- src/python/dxpy/asset_builder.py
- src/python/dxpy/scripts/dx_build_app.py
Add `20.04` asset builder.
Remove unsupported `18.04` remote builder, add `16.04` version `1` remote builder.
> 16.04 v1 remote builders. 20.04 asset builder

- src/python/requirements.txt
gnureadline fails to build with recent macOS catalina and clang updates. Bumping to 8.0.0 helps for Python < 3.8, as their are prebuilt wheelfiles hosted on pypi. For Python > 3.8, gnureadline is probably not required since homebrew managed python installs come with gnu readline, not libedit like the macOS system python.
> Bump gnureadline to 8.0.0, install for Python < 3.9

- doc/examples/ua/manifest.json
- src/Makefile
- src/ua/main.cpp
- src/ua/options.cpp
- src/ua/options.h
This adds support for uploading files described by a manifest. This is required in order to add support for parallel upload of outputs to dxWDL.
One thing to note: I tested this on 18.04, but I am not able to get this to compile on 20.04. Specifically, there is an error when using openssl 1.1, and there is no openssl 1.0 package available for 20.04.
> Add support to UA for JSON manifest

- src/ua/chunk.cpp
- src/ua/main.cpp
- src/ua/options.cpp
- src/ua/options.h
Remove round-robin DNS upload strategy from upload agent. Was originally implemented for the deprecated v1 upload. 
Most likely the cause of https://github.com/dnanexus/dx-toolkit/issues/581
> DEVEX-1796 remove round-robin from UA upload

- src/python/scripts/dx-upload-all-outputs
- src/python/setup.py
- src/python/test/file_load/basic/dxapp.json
- src/python/test/file_load/basic_except/dxapp.json
- src/python/test/file_load/benchmark/dxapp.json
- src/python/test/file_load/deepdirs/dxapp.json
- src/python/test/file_load/file_optional/dxapp.json
- src/python/test/file_load/parseq/dxapp.json
- src/python/test/file_load/prefix_patterns/dxapp.json
- src/python/test/file_load/vars/dxapp.json
- src/python/test/file_load/with-subjobs/dxapp.json
- src/python/test/file_load/xattr_properties/dxapp.json
- src/python/test/file_load/xattr_properties/run.sh
- src/python/test/test_dx_bash_helpers.py
- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
Wrap `xattr` import in a try/catch in `dx-upload-all-outputs`. Was causing some test failures. 
Upgrade some of the dxclient test applets to Ubuntu 20.04 and Python 3. 
Fix a few dxclient workflow tests which require waiting for analysis execution and stage doc creation.
> xattr import fix / test fixes

- src/java/src/main/java/com/dnanexus/DXEnvironment.java
- src/java/src/main/java/com/dnanexus/DXFile.java
- src/java/src/main/java/com/dnanexus/DXHTTPRequest.java
- src/java/src/test/java/com/dnanexus/DXHTTPRequestTest.java
Hi, this is a follow-up to Case #00026075.
Generally, the sole problem is in the constant creation of `HttpClient` overall and specifically whenever `FileApiInputStream` empties its buffer (see [DXFile:577](https://github.com/dnanexus/dx-toolkit/blob/master/src/java/src/main/java/com/dnanexus/DXFile.java#L577) for ex).
This leads to the creation of a new connection pool and leasing a single connection. Then without closing the `HttpClient` we just leave it to GC to cleanup. Since the default protocol for `HttpClient` is `HTTP 1.1` and [it requires any connection to be persistent by default](https://tools.ietf.org/html/rfc2616#section-8.1.2) we can't rely on the server or client to terminate TCP session unless we provide `Connection: close` header explicitly and we can't rely on any …
> DEVEX-1894 Connection (socket) leak in DxFile

- src/Makefile
Upgrade to proot 5.2 from udocker2 fork
> Upgrade proot for kernel upgrade

- src/python/dxpy/scripts/dx_app_wizard.py
- src/python/test/test_dx_app_wizard.py
Update the default `runSpec` from Ubuntu 16.04 v1 to Ubuntu 20.04.
> Update dx-app-wizard default to Ubuntu 20.04

- src/python/dxpy/bindings/dxproject.py
- src/python/dxpy/cli/parsers.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/utils/describe.py
- src/python/test/test_dxpy.py
This PR adds a new `--database-ui-view-only` project flag for `update` (which can be displayed via `describe`), as well as support for the flag in our `dxpy` bindings (for `new` and `update`)
The CLI parses the `database-ui-view-only` flag into `databaseUIViewOnly`, which is ultimately passed to the apiserver as an argument.
> TIP-2332: New databaseUIViewOnly project flag to dx-toolkit

- CHANGELOG.md
- src/python/dxpy/bindings/dxglobalworkflow.py
- src/python/dxpy/scripts/dx.py
This PR fixed the issue that when `dx run <globalworkflow> --project project-XXXXXX` does not submit the global workflow to the target project. Similar problems are observed when using flags '--destination', '--folder'.
It is caused by missing the 'project' argument when updating run inputs for the underlying workflow, and it is now fixed by bringing the 'project' argument back.
[APPS-554: Submitting globalworkflow does not respect project flag](https://jira.internal.dnanexus.com/browse/APPS-554)
> Apps-554 set globalworkflow project

- src/python/dxpy/bindings/dxdatabase_functions.py
- src/python/dxpy/bindings/dxfile.py
- src/python/dxpy/bindings/dxfile_functions.py
Support FIPS enabled Python https://github.com/dnanexus/dx-toolkit/issues/702
Refactor `hashlib.md5()` --> `hashlib.new('md5', usedforsecurity=False)`
`usedforsecurity` param is ignored on Python versions < 3.9. md5 is allowed in this context since it is only used for file part checksums file, not security.
> DEVEX-1961 Support FIPS enabled Python

- src/python/dxpy/bindings/dxdatabase_functions.py
- src/python/dxpy/bindings/dxfile.py
- src/python/dxpy/bindings/dxfile_functions.py
- src/python/dxpy/compat.py
For FIPS enabled python compatibility, attempt to pass the `usedforsecurity=False` param.
> DEVEX-1961 Add md5_hasher() to compat functions

- src/python/dxpy/scripts/dx.py
`dryrun_request_input = dict(**request_input, dryRun=True)` causes `SyntaxError: invalid syntax` on Python 2.
> Fix python 2 syntax error in archive

- Readme.md
- src/python/dxpy/scripts/dx.py
This PR adds path resolution and support to the `dx list database files` command.  Previously, the command only supported the database input as an object hash ID, but now it also supports database input as a path, e.g. `dx list database files test/edtest18`.
Here is examples from testing locally:
```
root@localhost:/dx-toolkit# dx ls test/
a
edtest18
root@localhost:/dx-toolkit# dx list database files test/doesnt_exist
ResolutionError: Unable to resolve "doesnt_exist" to a data object or folder name in '/test'
root@localhost:/dx-toolkit# dx list database files test/edtest18
0 411c7b8f/database-G55pFf00KY15QGJXBg1vVqxz/test_table/
root@localhost:/dx-toolkit# dx list database files database-G55pFf00KY15QGJXBg1vVqxz
0 411c7b8f/database-G55pFf00KY15QGJXBg1vVqxz/test_table/ …
```
> TIP-2525: Add support for database path as input to dx list database files

- src/python/dxpy/__init__.py
Remove no longer used `match_hostname` import which fails to import as of urllib3 1.26.8 https://github.com/urllib3/urllib3/releases/tag/1.26.8.
https://github.com/dnanexus/dx-toolkit/issues/746
> DEVEX-2035 Remove unused match_hostname import

- src/python/dxpy/scripts/dx.py
Fix help message to `dx ssh`. 
Fix parsing of `--allow-ssh` to check for any `None` entries and then filter them out instead of iterating.
> DEVEX-2013 --allow-ssh fixes

- src/python/dxpy/bindings/dxfile_functions.py
- src/python/test/test_dxpy.py
Fix recursive folder download. Current broken behavior example where an empty subfolder is created for folders sharing the same prefix. 
```
$ dx ls -l |grep xyz
xyz/
xyz123/
$ dx download -r xyz
$ tree xyz
xyz
└── 23
```
> DEVEX-2023 Fix recursive folder download

- src/python/test/test_dxclient.py
Reverts dnanexus/dx-toolkit#758 - let's to back to using the smoke test app for this test.
> Revert "Switch app launched in test_dx_run_app"

- contrib/perl/lib/DNAnexus/API.pm
- contrib/ruby/lib/dxruby/api.rb
- src/R/dxR/R/api.R
- src/api_wrappers/wrapper_table.json
- src/cpp/dxcpp/api.cc
- src/cpp/dxcpp/api.h
- src/java/src/main/java/com/dnanexus/DXAPI.java
- src/python/dxpy/api.py
- src/python/dxpy/toolkit_version.py
These are Data Object methods that I missed the first time. They are expected on all [DNAnexus data objects](https://documentation.dnanexus.com/developer/api/introduction-to-data-object-classes).
> PTFM-31003 Add missing dbcluster methods to API wrappers

- src/python/dxpy/scripts/dx.py
Optimize the `project-xxxx/listFolder` call to only return folders, not objects in case the folder contains thousands of objects. Safe to do as this call is only checking that the folder argument to `dx cd` exists.
> DEVEX-2055 Only query for folder when checking folder exists in `dx cd`

- src/python/dxpy/bindings/dxapplet.py
Previously by default the `project` parameter was ignored in `dx run` since it was not possible to launch jobs in another project, this is now possible if `--detach` is specified.
> DEVEX-2080 Set project argument for executable launched from a job in`--detach` mode

- src/python/dxpy/cli/download.py
Not recommended, but `dx get file-xxxx` does work to download files. 
```
$ dx get file-xxxx
File "/Users/kjensen/Library/Python/3.8/lib/python/site-packages/dxpy/cli/download.py", line 98, in download_one_file
symlink_max_tries=args.symlink_max_tries)
AttributeError: 'Namespace' object has no attribute 'symlink_max_tries'
```
> DEVEX-2094 Supply default 15 symlink_max_tries if not present in args

- CHANGELOG.md
- src/python/dxpy/__init__.py
- src/python/dxpy/exceptions.py
* Different types of SSL errors are raised depending on Python version,
* add all of them to prevent `dx upload` failing with bad internet connection
> APPS-1285 add all SSL error types as retryable exceptions

- CHANGELOG.md
- src/python/dxpy/scripts/dx.py
- src/python/test/test_dxclient.py
* add `--on-behalf-of <org>` optional parameter for `dx new user`; the API is passed the org in the "provisioningOrg" field, which causes the welcome email to contain the correct org id.
* add a test
> APPS-1316 add --on-behalf-of parameter for `dx new user`

- src/python/dxpy/nextflow/nextflow_builder.py
- src/python/dxpy/nextflow/nextflow_templates.py
- src/python/dxpy/scripts/dx_build_app.py
- src/python/dxpy/templating/templates/nextflow/dxapp.json
- src/python/dxpy/templating/templates/nextflow/src/nextflow.sh
Added file or directory support.
In order to use file, we can specify file as an input, but in case the input is string (happen when defined argument can be file or directory) we can use string:
dx://project-yyyy:file-zzzz
or dx://project-yyyy:/path/to/file
In order to use directory, string must contain path to a directory:
dx://project-xxxx:/path/to/folder/ 
in order to have multiple files in input, we can use wild cards: dx://project-wwww:/data/*.fa
> APPS-1250 nextflow - Added file or directory support.

- src/python/dxpy/nextflow/nextflow_utils.py
`exec` is reserved in python 2.
> Rename var from reserved 'exec' keyword

- src/python/dxpy/nextflow/nextflow_utils.py
The `exist_ok` parameter was added in Python 3.2.
Replicate the behavior of `os.makedirs(exist_ok=True)` by checking if the OSError raised is `EEXIST`.
> Python 2 compat fix for `os.makedirs()`

- src/python/requirements.txt
Pin to argcomplete version to < 2.0, except for Python >= 3.10
> DEVEX-2137 Fix TestDXTabCompletion tests

- src/python/test/test_dxclient.py
- src/python/test/test_nextflow.py
Switch back working directory after running relative path test.  
Skip windows-only test on other platforms.
> Fix nextflow relative path test

- src/python/dxpy/scripts/dx_build_app.py
This fixes a test failure due to [UnicodeDecodeError](https://jenkins-vstg.internal.dnanexus.com/view/dx-toolkit%20release%20board/job/dx-toolkit/job/dxpy-master-integration-tests-on-staging-16.04-python2/1728/console).
Successful tests:
- [py3](https://jenkins-vstg.internal.dnanexus.com/view/dx-toolkit%20release%20board/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/202/)
- [py2](https://jenkins-vstg.internal.dnanexus.com/view/dx-toolkit%20release%20board/job/dx-toolkit/job/dxpy-master-integration-tests-on-staging-16.04-python2/1731/)
> APPS-1431 Fix to reading a file in py2 environment

- CHANGELOG.md
- src/python/dxpy/scripts/dx_build_app.py
--extra-args overrides --destination (name only)
warning is printed. Also fixed wrong error message when -f or -a was not specified (as dx-toolkit preferred destination over extra-args, but our backend handled it the other way around.)
> APPS-1412 Fixes to setting name in dx build

- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
The result:
```
test_get_applet_field_cleanup (test_dxclient.TestDXGetAppsAndApplets) ... skipped 'skipping per DEVEX-2161'
----------------------------------------------------------------------
Ran 1 test in 0.000s
OK (skipped=1)
```
(it's the same for the other test)
> DEVEX-2161 Skip tests

- src/python/dxpy/__init__.py
Global workflow [describe output](https://documentation.dnanexus.com/developer/api/running-analyses/global-workflows#api-method-globalworkflow-xxxx-yyyy-describe) always contains resource container ID which contains the underlying workflow (one per region). We can use it here as a hint to describe to speed up query response.
> APPS-1472 Add a resources container as a hint when describing underlying workflows

- src/python/dxpy/bindings/dxdatabase_functions.py
TIP-3025 - Fixed dx get database
Fixed how dx-toolkit dx get database commands reads from api server now that there is an API proxy interceptor.
> TIP-3025 - Fixed dx get database

- src/java/src/main/java/com/dnanexus/DXFile.java
- src/java/src/test/java/com/dnanexus/DXFileTest.java
Use the project-id of `DXFile()` if already known, else retrieve it to use in subsequent `file-xxxx/describe` API calls within `DXFile()`. Also use this project-id in `file-xxxx/download` API calls.
Also retrieve the file size once at the beginning instead of when calculating byte range.
> DEVEX-2186 Use project ID for file-xxxx/describe API calls within dxjava DXFile

- src/python/test/test_extract_dataset.py
Different error message in Py2: "--list-entities cannot be specified with: [**u**'--sql']" I did adjusted the negative tests. 
https://jira.internal.dnanexus.com/browse/SCIPROD-1183
> SCIPROD-1183: dx extract_dataset - fixing Py2 failed tests

- CHANGELOG.md
- src/python/dxpy/bindings/dxapplet.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/utils/describe.py
* pretty-print "Preserve Job Outputs Folder" in `dx describe` for analysis and job
* new `dx run` args `--preserve-job-outputs` and `--preserve-job-outputs-folder`
> DEVEX-2159 Support for preserveJobOutputs in "dx run" and "dx describe"

- CHANGELOG.md
- build/run_java_integration_tests.py
- src/java/src/main/java/com/dnanexus/ArchivalState.java
- src/java/src/main/java/com/dnanexus/DXEnvironment.java
- src/java/src/main/java/com/dnanexus/DXFile.java
- src/java/src/main/java/com/dnanexus/DXJSON.java
- src/java/src/main/java/com/dnanexus/DXProject.java
- src/java/src/main/java/com/dnanexus/DXSearch.java
- src/java/src/main/java/com/dnanexus/RunSpecification.java
- src/java/src/main/java/com/dnanexus/UnarchivingRate.java
- src/java/src/test/java/com/dnanexus/DXProjectTest.java
- src/java/src/test/java/com/dnanexus/DXSearchTest.java
**Java binding changes:**
* new field in `dx describe`
* possibility to search using `archivalState` field
* possibility to (un)archive files
* suitable tests
* minor fixes in javadoc strings to be compatible with Java 11 and HTML5
**Other changes:**
* make `build/run_java_integration_tests.py` compatible with Python 3
> DEVEX-2226 File (un)archive support in DXJava

- CHANGELOG.md
- src/python/dxpy/bindings/dxapplet.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/utils/describe.py
For the time being the feature is not yet fully ready on backend side and it should be temporarily reverted from dx-toolkit.
This reverts commit 99ae98f325ba50490cb90b2d0049927e3a5efaa2.
> DEVEX-2159 Temporarily revert preserveJobOutputs functionality

- CHANGELOG.md
- src/python/dxpy/cli/exec_io.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/templating/utils.py
* Fixed `dx-app-wizard` script on Windows
* Fixed non-working tab completion in interactive executions on Windows
* Fixed tab completion in interactive execution of `dx-app-wizard` on all OSs
* In MacOS tab completion in interactive executions now works with `libedit` bundled in the OS and does not require externally installed GNU `readline`
> DEVEX-2165 Fix dx-app-wizard and tab completion on Windows

- CHANGELOG.md
- src/python/requirements.txt
> DEVEX-2240 Bump allowed cryptography dxpy dependency version to 40.0.x

- src/python/dxpy/dx_extract_utils/retrieve_allele_schema.json
- src/python/dxpy/dx_extract_utils/retrieve_annotation_schema.json
- src/python/dxpy/dx_extract_utils/turbo_filter.py
- src/python/test/CLIGAM_tests/test_payload.py
This PR removes the "compound" structure from the assay filter object, resulting in a flat filters structure.  All fields are related to each other by "and".  Modified allele input validation to prevent location and rsid being provided together.  This fixes the issue caused by location being provided alone and failing due to an empty fields object, as well as the issue caused by geno_bins only being present in the second part of a compound but not the first.
> Sciprod 1258 flat allele payload

- src/python/dxpy/__init__.py
`file()` is no longer present in Python 3
> DEVEX-2264 Replace obsolete built-in file() method with open()

- src/python/requirements_test.txt
- src/python/test/test_dxpy.py
Removing pyopenssl from requirements_test.txt for now, since it was only used by the disabled test `test_ssl_options` - and our pinned pyopenssl version was causing an import failure in test_dxpy.py.
> DEVEX-2263 Fix ImportError in test_dxpy.py

- src/python/dxpy/dx_extract_utils/input_validation.py
- src/python/test/extract_assay_germline/test_input/malformed_json/annotation/consequences_no_required.json
- src/python/test/extract_assay_germline/test_input/malformed_json/annotation/putative_no_required.json
- src/python/test/test_extract_assay.py
Hi folks,
This PR addresses a gap in the input validation for the consequences and putative_impact fields in the annotation filters.  The spec specifies that these fields cannot be provided without at least one of gene_name, gene_id, or feature_id, which means there was an edge case where allele_id was provided with consequences or putative_impact, but none of the three mentioned above, and would fail to be blocked by input validation.  This change adds that validation, and also adds a test for each of the two fields
> Sciprod 1232 validate consequences and putative_impact

- src/python/dxpy/cli/dataset_utilities.py
The cause of the issue was that the quotechar was set to the double quote character.  The quotechar does the following: A one-character string used to quote fields containing special characters, such as the delimiter or quotechar, or which contain new-line characters. It defaults to '"'.
Since the rsid field has double quotes in it, as it is a list of strings, the quotechar was being applied on either side of every double quote in the values.  By changing the quotechar to "|", it will only get applied in the event that either a tab or a "|" character exists in a column value
> allowing quotechar to be manually set for writing tsv output

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/input_validation.py
- src/python/test/test_extract_assay.py
Hi Folks,
This PR fixes issues with python 2.7 compatibility that we discovered during testing.  Essentially, python 2 has a unicode type that is distinct from the string type, so some type checks were failing in python 2 because isinstance(<unicode string>,str) returns false in python 2.  The code now checks if the python major version is 2 or 3, and in the case where it is 2, checks if the object is either a string or unicode object
> Sciprod 1277 python 27 compat

- src/python/dxpy/bindings/dxproject.py
- src/python/dxpy/utils/describe.py
- src/python/test/test_dxpy.py
DEVEX-2307
APPS-1462
* added support for externalUploadRestricted to DXProject.new(), .update()
* added it among recognized fields
* extended existing tests with this parameter
> DEVEX-2307: add-project-new-external-upload-flag

- src/python/dxpy/cli/dataset_utilities.py
Hi Folks,
This change forces the python2 interpreter to interpret the quotechar in the csv_from_json function to be interpreted as a str type and not as unicode.  I tested both python2 and python3 and all unit tests pass.
More details in the ticket description [here](https://jira.internal.dnanexus.com/browse/SCIPROD-1413)
> forcing quotechar to be interpeted as a string by python 2

- src/python/dxpy/cli/dataset_utilities.py
The `vcf_meta_information_unique` table and descriptor no longer have the `info_format_fields` column used to extract the meta information. It has been replaced by `Field, ID, Type, Number, Description`. The `extract_assay somatic --retrieve-meta-info` option has been updated around the table changes.
- `vcf_meta_information_unique` `Field, ID, Type, Number, Description` columns are used to query the meta information.
- Meta information is output as a tab-delimited table.
> SCIPROD-1334 Update somatic assay meta info query and output

- src/python/dxpy/cli/dataset_utilities.py
Updated quotechar in extract_assay somatic variant output from "|" to "" with no quoting.
> SCIPROD-1505 extract assay somatic info field quotechar

- src/python/dxpy/cli/dataset_utilities.py
`extract_assay somatic --retrieve-variant` fails in Python 3.11. Removed empty quotechar string parameter value.
> SCIPROD-1522 extract_assay somatic --retrieve-variant output fix

- src/python/dxpy/scripts/dx.py
- src/python/dxpy/utils/describe.py
- src/python/test/test_dxclient.py
This PR is to amend the workaround for PTFM-35818 added in [pull/1007](https://github.com/dnanexus/dx-toolkit/pull/1007) 
With changes in this PR, when doing `dx describe analysis --json --verbose`, default description fields will also be included along with the newly added fields related to system requirements, same as when doing `dx describe analysis --verbose`
> APPS-2076 add default fields to dx describe analysis json verbose

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/scripts/dx.py
Hi Folks,
This PR adds validation of the input cohort ids.  It finds the main entity of the dataset (generally referred to as the cohort ID because the main entity and field can be different for different types of dataset) and creates a vizserver payload to search the dataset for entries with matching cohort IDs, returning the discovered cohort IDs.  If the user has provided ids that are not found in the dataset, an error message is displayed specifying which IDs were not found.
> SCIPROD-1583 Logic added to create_cohort to validate cohort ids via vizserver search

- src/python/test/test_create_cohort.py
Hi Folks,
This is a quick test of the resolve_validate_record_path function.  It compares the returned sql to an expected output.  It would be able to detect if there is any change to that output caused by anything merged in the future.  It isn't an exhaustive test of all possible configurations of the payload, however.
> SCIPROD-1602 creating test for cohort query api

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/cohort_filter_payload.py
Raise exception and exit with error when a cohort filter has primary entity and field logic that is not "and".
> SCIPROD-1585: [CLIBCO] error for non-and logic on primary entity and field

- src/python/dxpy/scripts/dx.py
in "dx run --preserve-job-outputs", as root exectuion R's root job or root analysis' stages complete, R's regular outputs will be moved to R's regular output folder.
> DOCS-2028 dx run --preserve-job-outputs: add docs

- src/python/dxpy/nextflow/ImageRefParser.py
- src/python/test/test_nextflow_ImageRefParser.py
For `dx build nextflow` functionality enabling caching of docker images on the platform at compile time.
This PR adds classes to parse docker image reference in the forms of dx file path/ID or docker image/tag/digest and combinations thereof
> APPS-2138 parse container image ref

- src/python/dxpy/cli/dataset_utilities.py
Fix `extract_assay somatic` no assay of type error message
- Fixed string format typo
- Use `friendly_assay_type` for both no assay of type error messages
> SCIPROD-1713: fix extract_assay somatic no assay of type error message

- src/python/dxpy/cli/dataset_utilities.py
`extract_assay germline` results are ordered by chromosome and starting position. Chromosome order is first numeric and then string.
> SCIPROD-1570: order extract_assay germline results

- src/python/dxpy/bindings/apollo/vizserver_client.py
- src/python/dxpy/cli/output_handling.py
- src/python/test/test_extract_expression.py
Hi folks,
This change tests the write_expression_output function.  There are two positive tests that ensure the output is correct with and without the --sql flag, and several negative tests to ensure that the function rejects incorrect configuration.  Please let me know if there are any additional tests that you would like to be part of this ticket.
Thanks,
Joe
> Sciprod 1672 test output

- src/python/test/test_extract_assay.py
Added duplicate rsid input unit test for `extract_assay`.
> SCIPROD-1673: extract_assay duplicate rsid unit test

- src/python/dxpy/bindings/apollo/expression_matrix_transformation.py
- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/cli/output_handling.py
- src/python/test/test_extract_expression.py
Hi folks,
This PR adds a function which converts the regular vizserver output into a "wider" format, with one column for sample ID, and a column for each feature_id, with the contents of those columns being the expression value.  I'm going to make a few quick unit tests for this, just so I can be sure it works on input with multiple samples, especially if the samples have overlapping feature ids.
Thanks,
Joe
> SCIPROD-1731 function created for widening output data table

- CHANGELOG.md
- src/python/doc/dxpy.rst
- src/python/dxpy/__init__.py
- src/python/dxpy/bindings/dxfile.py
- src/python/dxpy/cli/cp.py
- src/python/dxpy/exceptions.py
- src/python/dxpy/packages/__init__.py
- src/python/dxpy/scripts/dx.py
- src/python/dxpy/scripts/dx_build_app.py
- src/python/requirements.txt
- src/python/requirements_test.txt
- src/python/test/test_dx_completion.py
- src/python/test/test_dxasset.py
- src/python/test/test_dxclient.py
- src/python/test/test_dxpy.py
- src/python/test/test_dxpy_utils.py
Remove both `requests` and `cryptography` from dxpy requirements. 
Fixed pytest warnings and removed some python2 specific code.
> COMPUTE-219 Remove dxpy dependencies requests and cryptography

- CHANGELOG.md
- src/python/dxpy/bindings/apollo/vizclient.py
Hi folks,
Super simple change that prevents the "variable referenced before assignment" traceback that was being shown to the user when there is insufficient permissions for the dataset.  Moving the return inside the try block means that it will only run if hte response variable has actually been set.
Thanks,
Joe
> SCIPROD-1870 cliexpress insufficient permissions traceback suppression

- CHANGELOG.md
- src/python/dxpy/app_builder.py
- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/filter_to_payload.py
- src/python/dxpy/dx_extract_utils/input_validation.py
- src/python/dxpy/executable_builder.py
- src/python/dxpy/scripts/dx_build_app.py
- src/python/dxpy/workflow_builder.py
- src/python/test/test_dxclient.py
- src/python/test/test_extract_assay.py
Removed references of `hom-alt` type, updated json.help string and added test covering `--retrieve-genotype` flag (runs locally).
> SCIPROD-1892 [GENOMOD] remove hom-alt genotype type

- src/python/test/test_extract_assay.py
Updated `dx extract_assay germline` unit tests for GENOMOD.
- Added genotype location filter test
- Updated `location_filter` arguments
- Updated expected descriptor
- Added `ref`, `half`, `no-call` retrieve genotype test
- Parameterized genotype retrieval test on v1.0 and v1.0.1 datasets
> SCIPROD-1894: [GENOMOD] update dx extract_assay germline unit tests

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/germline_utils.py
- src/python/dxpy/dx_extract_utils/input_validation.py
Updates to support `dx extract_assay germline --retrieve-genotype` 
- Exclude genotype and allele table query query when alternate genotypes types are not requested
- Include `DISTINCT` option if originally included after harmonization
> SCIPROD-1984: [GENOMOD] update `dxpy` `extract_assay` SQL query harmonization

- src/python/dxpy/scripts/dx.py
Updated `dx extract_assay germline` `--retrieve-genotype` help string to explain "half" genotypes where there is no allele ID.
> SCIPROD-2007: [GENOMOD] update `dx extract assay germline` docstrings

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/dx_extract_utils/germline_utils.py
- src/python/dxpy/dx_extract_utils/input_validation.py
- src/python/test/test_extract_assay.py
Updated genotype inference in `dx extract_assay germline --retrieve-genotype` to use loci from the allele table to determine missing samples to infer excluded genotype types.
> SCIPROD-2016: [GENOMOD] `dx extract_assay germline --retrieve-genotype` inference use alleles to determine loci

- src/python/dxpy/cli/dataset_utilities.py
- src/python/dxpy/cli/output_handling.py
removing `#` from `--json-help` text:
```
#
{
"sample_id": ["s1", "s2"],
"allele_id": ["1_1000_A_T","2_1000_G_C"],
"genotype_type": ["het-ref", "hom", "het-alt", "half"]
}
```
> SCIPROD-2031 [GENOMOD] pretty print example filer JSON

- src/python/dxpy/nextflow/ImageRef.py
Requires `sudo` access in the integration test env.
> Fix docker integration test for test env

- src/python/dxpy/cli/exec_io.py
- src/python/dxpy/utils/exec_utils.py
- src/python/dxpy/utils/file_load_utils.py
- src/python/dxpy/utils/local_exec_utils.py
- src/python/test/test_dx_app_wizard.py
- src/python/test/test_dx_bash_helpers.py
- src/python/test/test_dxclient.py
Fixes #1405
Python 3.13 [removed the `pipes` module](https://docs.python.org/3/whatsnew/3.13.html#removed-modules-and-apis)
> DEVEX-2424 replace pipes for python 3.13

- src/python/test/test_dxpy.py
Fix allowedExecutables default value changed in apiserver
Successful test: https://jenkins-vstg.internal.dnanexus.com/view/dx-toolkit%20release%20board/job/dx-toolkit/job/dxpy-branch-integration-tests-on-staging-20.04-python3/843/console
> PTFM-38891 Fix test for allowedExecutables default value

- src/python/dxpy/bindings/apollo/vizclient.py
New DataTooLarge error is thrown from apiproxy if we encounter vizserver response larger than 512MB. Currently it returns as InternalError.
> TIP-3908 Handle DataTooLarge error from vizserver

- src/python/dxpy/bindings/dxfile_functions.py
https://jira.internal.dnanexus.com/browse/PTFM-39450
`_verify_per_part_checksum_on_downloaded_file` was incorrectly called with an extra positional argument
> PTFM-39450: dxpy symlink download fix

- src/python/dxpy/bindings/dxfile.py
Cache the return of `object_exists_in_project()` in `DXFile.read()` at `DXFile._exists_in_proj` if the file exists in the `DXFile._proj` attribute. Avoids excessive `/file-xxxx/describe` calls for many `read()` calls. 
Fix behavior where `object_exists_in_project()` could have been called even if `self.get_proj_id() ` is `None`.
> DEVEX-2412 Cache DXFile._proj if found in DXFile.read()

- CHANGELOG.md
- src/python/dxpy/__init__.py
https://jira.internal.dnanexus.com/browse/COMPUTE-1113
Reduce frequency of retrying throttled requests if apiserver continues to return 429/503 response code over multiple attempts.
[Java sdk](https://github.com/dnanexus/dx-toolkit/blob/master/src/java/src/main/java/com/dnanexus/DXHTTPRequest.java#L412) already has such increased backoff strategy
> COMPUTE-1113: Increase backoff timeout for throttled requests over attempts

- CHANGELOG.md
- Readme.md
- src/R/dxR/R/dxinit.R
- src/python/dxpy/__init__.py
[COMPUTE-1235](https://jira.internal.dnanexus.com/browse/COMPUTE-1235)
- Handle 429 response code in R sdk.
- Add support to existing `alwaysRetry` option that previously was assigned but never used.
- Fix calculating increased backoff in dx.py to have int value of seconds instead of float in some cases.
> COMPUTE-1235: Handle 429 response code in R sdk

- CHANGELOG.md
- src/java/src/main/java/com/dnanexus/DXHTTPRequest.java
`NullPointerException` happened when I tried to [use dxApi in dxCompiler](https://github.com/dnanexus/dxCompiler/actions/runs/14089210499/job/39590964151).
Seems that in case when there is some network error response is not initialized and statusCode is still null and can't be used with integer comparison.
with that fix compiler was built and tested w/o errors https://github.com/dnanexus/dxCompiler/actions/runs/14132661095
> COMPUTE-1237: Fix java sdk to handle network errors when there is no response

- src/cpp/dxcpp/dxcpp.cc
Changes:
- The file `src/cpp/dxcpp/dxcpp.cc` was updated to handle the 429 http error the same as the 503 is handled
> Update dxcpp.cc to retry on 429 http error

- src/python/test/test_dxclient.py
https://jira.internal.dnanexus.com/browse/APPS-3152
Several tests in `test_dxclient.py` started failing recently due to changes brought by [TIP-3998](https://jira.internal.dnanexus.com/browse/TIP-3998). To ensure the affected test can be executed daily, I am updating the expected values returned by `org_find_members` (the method started returning an additional key:value pair `'treManagement': False`).
* [Passing run](https://jenkins-vstg.internal.dnanexus.com/view/Traceability%20Platform%20Tests/job/RTM/job/dx-toolkit_traceability_tests_isolated_master/15/) of the affected suite ✅
> APPS-3152: Update test_dxclient

- src/python/dxpy/__init__.py
Add support for using `apiserver` as a hostname for apiserver instead of `localhost` and `127.0.0.1` only to support running tests within a container composition that uses `apiserver` as a hostname of apiserver.
> [PTFM-40226] Enable running `dxpy` tests within a container composition
